### ISSUE TITLE
Function name "main" not used in single file examples

### ISSUE THREAD

**Issue by garyburd** [golang/gddo#132]
From John Blau

On http://godoc.org/code.google.com/p/go.net/websocket#example-Handler there is an error.

    func ExampleHandler(){  should be func main(){
 
If you click the ‘play’ link, the version that loads is correct.

The standard godoc tool does the same thing.

**Comment by LaPingvino** [comment]
func main, not func Main, right?

**Comment by garyburd** [comment]
yes, main

**Comment by LaPingvino** [comment]
@garyburd can you give a look if this is an acceptable way to fix this, and if I missed something? It seems to work well where I tested it, but maybe I missed some corner cases.

**Comment by garyburd** [comment]
Fixed by 9f70e16d88bc3af0685c69788dca18545c909622
