### ISSUE TITLE
Integration with Dash

### ISSUE THREAD

**Issue by Kapeli** [golang/gddo#149]
I'd like to integrate GoDoc into [Dash](http://kapeli.com/dash). In a nutshell, users would be able to download docs from godoc.org and Dash would keep them updated and so on.

**Searching issues**
As far as I can tell, the search API searches only inside the synopsis of the packages. Is there any way to search by import path?

**Versioning**
Is there any API that gives the date of the last update for a page? Ideally, this would be only when the page actually changes and not when someone presses "Refresh now".

**Comment by drewwells** [comment]
Is there any form of go integration in dash that uses the local godoc or at least godoc.org? While the docset is nice for looking up the standard packages, 90% of the time I have to go to local or public godoc.

**Comment by Kapeli** [comment]
Dash supports godoc.org, yes. Check out Preferences > Downloads > Go Docsets.

**Comment by drewwells** [comment]
How would I find the methods for https://github.com/mattn/go-sqlite3?

**Comment by garyburd** [comment]
This is the issue tracker for godoc.org, not Dasher. Please direct questions regarding Dasher to a different forum.

**Comment by drewwells** [comment]
Sorry, this issue is tracked on gddo not dash. Since it appears dash is
interacting with a zip archive rather than the godoc.org service, this
appeared to be the most appropriate place to ask the question. It was not
clear from the discussions how this issue was going to be resolved.
