### ISSUE TITLE
Feature: Dynamic badge

### ISSUE THREAD

**Issue by nathany** [golang/gddo#171]
**Pass/fail** https://github.com/golang/gddo/issues/107#issuecomment-23636890

* Package comments **(this is the important one)**
* presence of CHANGELOG?
* LICENSE file or found in the Readme? ![BSD](http://img.shields.io/badge/license-BSD-green.svg)
  `![BSD](http://img.shields.io/badge/license-BSD-green.svg)` 

Another possibility is a sort of "documentation coverage" score. See https://github.com/golang/gddo/issues/107#issuecomment-23634254.

**Comment by adg** [comment]
What's the status here?

**Comment by nathany** [comment]
I'm not sure if this is something we still want. 

I came at this from the angle of being able to make the badge dynamic, so what could we make it do. That doesn't seem like the best way to design features.

**Comment by adg** [comment]
Agree. Let's shelve it for now.
