### ISSUE TITLE
"The documentation displayed here is incomplete"

### ISSUE THREAD

**Issue by pwaller** [golang/gddo#175]
I think it's because of this [line in godoc](https://github.com/golang/gddo/blob/5dcc58d8df3e2c59b5afa358e99fd406574fa87c/database/database.go#L217).

The documentation used to work, and works for a fork of our project. Any chance we can get the limit bumped?

Original report: https://github.com/go-gl/gl/issues/155

![screenshot from 2014-06-11 09 13 27](https://cloud.githubusercontent.com/assets/438648/3241699/6d5f3672-f140-11e3-92a8-63b3338f57c7.png)

**Comment by wgj** [comment]
[github.com/softlayer/softlayer-go/services](https://godoc.org/github.com/softlayer/softlayer-go/services) still creates this issue.

**Comment by shurcooL** [comment]
That's a massive Go package, but it seems to load [okay](https://cloud.githubusercontent.com/assets/1924134/21663217/cbfa30ce-d2ac-11e6-819c-a71b61da7db4.png). What issue are you seeing?

**Comment by wgj** [comment]
Interesting. 
![screen shot 2017-01-04 at 3 42 53 pm](https://cloud.githubusercontent.com/assets/463564/21663360/8a954712-d294-11e6-8345-28d989e1d93a.png)

Chrome Version 55.0.2883.95 (64-bit)
MacOS 10.12.2

**Comment by shurcooL** [comment]
Okay, I am seeing "The documentation displayed here is incomplete. Use the godoc command to read the complete documentation." message now too.

**Comment by wgj** [comment]
fwiw, I just refreshed (godoc refresh link, not the browser) the page a moment ago.

**Comment by shurcooL** [comment]
@wgj, since this issue is quite old, can you create a new issue and mention #175 there?

The only solution that comes to my mind is to bump up the maximum allowed package size yet again. I'm not sure who owns gddo right now to be able to make such a decision.

**Comment by wgj** [comment]
Sure thing. Thanks for your help.

**Comment by jare19** [comment]
please update the max allowed package size, I like to use this site for docs but when it is unusable, it makes life rough! #488
