### ISSUE TITLE
The package http://godoc.org/github.com/ziutek/emgo/egroot/src/pkg/sync/atomic is not displayed

### ISSUE THREAD

**Issue by ziutek** [golang/gddo#184]
The package http://godoc.org/github.com/ziutek/emgo/egroot/src/pkg/sync/atomic is not displayed because it is categorized as mirror of the Go source tree. Open a new issue for this.

**Comment by tiborvass** [comment]
I think this issue can be closed :)

**Comment by adg** [comment]
@tiborvass why?
