### ISSUE TITLE
Modulecounts.com and number of packages available

### ISSUE THREAD

**Issue by edebill** [golang/gddo#186]
I'm the maintainer of modulecounts.com, which tries to give a very rough comparison of how many packages are available across different programming languages. I added the "Number of packages" number from http://godoc.org/-/index at a user's request back in June.

Since that number has begun growing so amazingly fast, some other users have objected because it seems to include quite a few forks of the same packages, rather than being a count of more truly unique packages.

Is there a "more correct" thing I should be reporting for Go? I haven't been able to find a package repository in the traditional sense. I don't want to exclude a language just because it's too easy to share code, but I also want to try to keep numbers as comparable as possible.

I realize that the github issues page for a site is not the normal forum for asking this sort of question. If there's a better place, please point me to it.

Regards,
Erik DeBill

**Comment by adg** [comment]
Closing this as I don't see an action to take. Happy to reopen if that's not the case.

**Comment by garyburd** [comment]
Here's a discussion about the godoc.org numbers reported on modulecounts.com:  https://github.com/mikeal/go-stats/blob/master/README.md
