### ISSUE TITLE
CSS: Use [r]em instead of px for font-size

### ISSUE THREAD

**Issue by jayschwa** [golang/gddo#196]
Relative units such as `em` or `rem` scale with the browser's default font size. `px` do not. I tend to set my browser's default font size a little larger, so it's a minor pet peeve when web pages don't respect / utilize it.

The `px` values are coming from Bootstrap, and I don't expect Bootstrap to change this anytime soon, so I guess this issue is mostly for posterity.

**Comment by adg** [comment]
I'm gonna close this because it's not something we have control over.
