### ISSUE TITLE
Searching using partial paths doesn't work for some packages

### ISSUE THREAD

**Issue by Kapeli** [golang/gddo#234]
Searching using partial paths doesn't work for some packages.

This works:
http://godoc.org/?q=astaxie%2Fbeego

This doesn't:
http://godoc.org/?q=PuerkitoBio%2Fgoquery

**Comment by garyburd** [comment]
Search on partial path does not work at all.  The first query works because the package synopsis contains the text "astaxie" and "beego".

**Comment by Kapeli** [comment]
Ah, sorry. I know we had a discussion regarding partial paths before. I thought you added support for it since the first query worked.

I'll close the issue.
