### ISSUE TITLE
Unnecessary empty line in type description

### ISSUE THREAD

**Issue by Thomasdezeeuw** [golang/gddo#243]
On the following page http://golang.org/pkg/sync/#Pool an unnecessary empty line is added to the code. It's probably because it contains unexported fields an a new line before the public fields, but it would be nice if this empty is not shown. The same happens in the text version of the page: http://golang.org/pkg/sync/?m=text (manual scrolling required).

Maybe this is an issue for the godoc parser, but I'm not sure.

**Comment by shurcooL** [comment]
This is an issue tracker for https://godoc.org, not https://golang.org/pkg. But your link points to the latter.

However, http://godoc.org/sync#Pool is equally affected.

**Comment by Thomasdezeeuw** [comment]
sorry about the link, but then the problem is likely to be in the go doc parser.

**Comment by garyburd** [comment]
This is an issue with the [go/doc](http://golang.org/pkg/go/doc/) package. Please create an issue at https://github.com/golang/go/issues.
