### ISSUE TITLE
`type error struct {...}` makes Index list methods of the type

### ISSUE THREAD

**Issue by tv42** [golang/gddo#244]
Something in this source is making godoc.org do weird things: http://godoc.org/github.com/alphazero/contextual

First guess would be this: https://github.com/alphazero/contextual/blob/1d18e8ac42a5e6e2e65dc02f44b93e48c8170bce/contextual.go#L30

```go
type error struct {
	msg string
}
```

Here's the index as it shows up right now:

```
Index
Constants
func ChildContext(p *context) (c *context, e Error)
func (e error) Error() string
func (e error) Is(errmsg string) bool
func NewContext() *context
type Component
func NewComponent() Component
type Container
type Context
type Contextual
type Error
```

Now, that source is silly but this still sounds like a bug in godoc.org.

**Comment by adg** [comment]
Actually, you had it right the first time. It's a bug in godoc.

**Comment by adg** [comment]
See golang/go#9860.
