### ISSUE TITLE
Display Usage constant in tools/cmd/* pages

### ISSUE THREAD

**Issue by reusee** [golang/gddo#245]
Some commands under tools/cmd put usage details in Usage constant, for example
http://godoc.org/golang.org/x/tools/cmd/callgraph
http://godoc.org/golang.org/x/tools/cmd/gomvpkg
http://godoc.org/golang.org/x/tools/cmd/gorename
It would be helpful if that constant is displayed on the page.

**Comment by shurcooL** [comment]
It would be helpful, but I'm not sure if it can be solved in the general case, because Usage may not always be a constant.

For example, `gorename` has no constant, usage is derived from the registered flags. `callgraph` has a constant, but its value is a string + another constant + another string.

**Comment by shurcooL** [comment]
See https://github.com/vieux/gocover.io/issues/1 for a similar request and more implementation details.

**Comment by garyburd** [comment]
How about adding a `go generate` tool that generates the package documentation string from the output of -help and updating the commands mentioned above to use this tool?

**Comment by adg** [comment]
Sounds like an elegant solution.
