### ISSUE TITLE
Proposal: Use wiki for documentation

### ISSUE THREAD

**Issue by garyburd** [golang/gddo#248]
I propose enabling the wiki for this repository for the purpose of documenting godoc.org.  Documentation that can be added to the wiki includes:

- Documentation for the go-source meta tag.
- API documentation  (currently in the README file)
- Plain text interface (currently on the about page)

To advertise the wiki, add links to the wiki from the README and the about page.

**Comment by adg** [comment]
I concur. I have enabled the wiki for this repo.
