### ISSUE TITLE
GitHub OAuth token

### ISSUE THREAD

**Issue by rjeczalik** [golang/gddo#254]
GitHub caps calls/hour to 60 for unauthorised requests. Applications using GitHub API typically work with `GITHUB_TOKEN` environment variable, if it's present they use the value for authorisation. Do we care enough to extend `gddo-server` with support for it or for support of GitHub authorisation in general? Would eventual PR be accepted?

The problem in action:

```
2015/03/03 16:35:15 web   fetch: 2872 ERROR: 403: API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (https://api.github.com/repos/rjeczalik/notify/git/blobs/e26014e9f0204f651fbdd1c33704b5d955d47d0a) github.com/rjeczalik/notify
```

**Comment by garyburd** [comment]
Copy config.go.template to config.go and update to include your credentials.

**Comment by rjeczalik** [comment]
I want to use account tokens (https://github.com/settings/tokens/new) and not the applications ones, as with the former I can limit what the `gddo-server` can access and what not.

What about two more flags: `-appid` and `-token`, if both are present `gddo-server` logs in as an app, if only `-token` is present it uses account token.

Making it configurable at runtime would simplify updating the server.

**Comment by garyburd** [comment]
The server can only access public data as currently written. There's nothing to limit.

The config file is a leftover from the days when godoc.org ran on App Engine. Moving the credentials to command line flags seems OK to me, but it's up to @nf.

**Comment by shurcooL** [comment]
I'll point to this relevant issue https://github.com/golang/gddo/pull/143#issuecomment-33450153, in case it's helpful.

**Comment by garyburd** [comment]
Converting to personal access tokens is useful because the tokens can have *more* access. I don't know why I didn't convert the last time the issue came up.  Again, this change is @nf's call.

**Comment by adg** [comment]
I think environment variables would probably be better, as they're not visible to `ps`.

But I'd also like to be able to pull the authentication token out of the Compute Engine Metadata service for the actual godoc.org deployment. Something like [this](https://github.com/golang/tools/commit/e83bc563341b00d5a331c0c3419b084ca6b36ab3#diff-dd77f7779420326cd5bb3e6807a438aaR45).
