### ISSUE TITLE
Look for branch or tag that matches version of Go on Launchpad

### ISSUE THREAD

**Issue by garyburd** [golang/gddo#26]
Look for branch or tag that matches version of Go.

* ~~Github~~
* ~~Google Project Hosting~~
* Launchpad
* ~~Bitbucket~~
* ~~Gitorious~~

**Comment by adg** [comment]
Google project hosting is going away, so I removed it from the list.

**Comment by garyburd** [comment]
Are people using the "go1" branch/tag feature these days?  I think we can close this.
