### ISSUE TITLE
Documentation text width could be larger

### ISSUE THREAD

**Issue by josselin-c** [golang/gddo#260]
Documentation for packages seem to takes only about half the screen width. This makes reading some struct definitions quite frustrating. See for example https://godoc.org/github.com/Shopify/sarama#Config

Would it be possible / a good idea to make the text area larger so we don't have to scroll horizontally?

**Comment by avrtno** [comment]
Past a point, increasing line length decreases reading speed. I suggest fixing the package instead of making everything on godoc slower to read.

**Comment by shurcooL** [comment]
As a point of reference, the source code seems to be about equally cut off when viewing in GitHub as well:

![image](https://cloud.githubusercontent.com/assets/1924134/7790362/c811584c-0239-11e5-947d-bc25c1e32bfc.png)

While I think godoc.org could be a little wider by default (maybe 10-20% more than it is now), in this case this package `sarema` package is primarily to blame for low readability. It should stay around 100~ or fewer characters wide, but it exceeds 120-140+ in many cases.

**Comment by adg** [comment]
I filed https://github.com/Shopify/sarama/issues/540

We should leave godoc.org as-is.
