### ISSUE TITLE
show large constant strings if the user wants to

### ISSUE THREAD

**Issue by minux** [golang/gddo#261]
See also golang/go#10257.

http://godoc.org/golang.org/x/tools/refactor/eg

I think even though the big Help const is not shown by default, the user
should still be able to see it. And that will be very useful in this particular
case.

**Comment by garyburd** [comment]
The documentation for eg should be fixed. See https://github.com/golang/gddo/issues/245#issuecomment-74403876 for one possible way to fix the documentation.

If there is interest in viewing long strings separate from the broken documentation issue, then we should add a link to the string in the source code.

**Comment by minux** [comment]
The issue I linked is about the eg documentation.

This issue is only about adding ability to showing the large const strings
to gddo.
Whether the package has broken docs or not is irrelevant here.
(Even it has broken docs style, not being able to show the string content
is still
a bug in gddo. It's a tool to show docs, not a tool to judge whether the
docs stylle
is good or bad.)

**Comment by shurcooL** [comment]
> If there is interest in viewing long strings separate from the broken documentation issue, then we should add a link to the string in the source code.

I think that's the way to go.

It can already be done for other identifiers. For example, http://godoc.org/golang.org/x/tools/refactor/eg#WriteAST has a link to the source, https://github.com/golang/tools/blob/af0a4481dd36113fd967a37a64d887d4b9d3425e/refactor/eg/eg.go#L282. So it's just a matter of adding support to link const identifiers to the source.

Separately, FWIW, gotools works:

http://gotools.org/golang.org/x/tools/refactor/eg#Help

**Comment by garyburd** [comment]
I have a change in progress to link all declarations to the source. It turns out that the database has source positions for a declarations, but it's unused for const and var.

**Comment by garyburd** [comment]
#262 adds a link to the source where the string literal can be viewed.

**Comment by garyburd** [comment]
Change 309f8824a968c3fd6379dee5810111363c23bcf9 is now live. The full help string is now one click away from the godoc.org page.
