### ISSUE TITLE
Directories issues

### ISSUE THREAD

**Issue by kpashka** [golang/gddo#265]
Test case - http://godoc.org/github.com/kpashka/goodbye

Bugs:
1. Recently I've did reorganization of subpackages, but gddo still displays old directories ("lib", "goodbye").
2. Not sure, but looks like new directories are added to the directories list (on main package page) after their first request at gddo. Kinda buggy, because users don't always know repo directory structure.

**Comment by rjeczalik** [comment]
Usually refreshing deleted directories removes them from index - you need to refresh each one separately. What would be helpful is recursive refresh: when a single package within project tree gets refreshed, whole project tree gets refreshed as well (maybe except */vendor/*, */Godeps/* paths).

**Comment by kpashka** [comment]
@rjeczalik Thanks for the advice. Actually, I tried to refresh old directories, and even checked them after more than hour - they still existed. But now it looks fixed, so I'm kinda confused.

**Comment by rjeczalik** [comment]
> But now it looks fixed, so I'm kinda confused.
@kpashka yup, I refreshed them they way I've described it above :)
