### ISSUE TITLE
Docs for old code being generated

### ISSUE THREAD

**Issue by bruth** [golang/gddo#269]
I recently changed the contents of the master branch with a new set of APIs, but documentation for the old APIs are still being shown even after a forced refresh.

- Repo: https://github.com/chop-dbhi/origins
- Docs: http://godoc.org/github.com/chop-dbhi/origins

**Comment by garyburd** [comment]
Godoc.org and the 'go get' command use the "go1" branch if present.  Either update the "go1" branch with the new code or remove the branch if you want to use "master".

**Comment by bruth** [comment]
Good to know. I just happened to name my old branch that without realizing the side effect. Thanks!
