### ISSUE TITLE
Command pages should link to source code

### ISSUE THREAD

**Issue by josharian** [golang/gddo#270]
https://godoc.org/rsc.io/benchstat does not contain any links to where the source code actually lives. Visiting rsc.io/benchstat redirects back to the godoc.org page.

Usually one can find a link by clicking on an identifier and then manually modifying the URL, but it seems reasonable to actually explicitly link to the source somewhere.

**Comment by garyburd** [comment]
Yeah, command pages should include a link to the the source.

The author of the package can fix this by providing a link to the source at rsc.io/benchstat or by using the [go-source meta tag](https://github.com/golang/gddo/wiki/Source-Code-Links) to specify repository's home page.

See the [yaml](https://gopkg.in/yaml.v2) package for an example of the first approach.  See the [golang.org/x/net](http://godoc.org/x/net) package for an example of the second approach.

**Comment by shurcooL** [comment]
@josharian, if I may suggest a 3rd way (requires user to perform it), one can replace the "doc" with "tools" in the aforementioned URL to see the source code of the Go package. I.e., http://gotools.org/rsc.io/benchstat.

**Comment by arnottcr** [comment]
@josharian, I think this may have been fixed since it was opened: (`main.go` directs one to [github](https://github.com/rsc/benchstat/blob/master/main.go))


![2019-04-04-054858_745x801_scrot](https://user-images.githubusercontent.com/2526260/55532424-5e180f00-569d-11e9-8167-1af8bdb3ef53.png)

**Comment by josharian** [comment]
Great.
