### ISSUE TITLE
index has zero width spaces in import paths

### ISSUE THREAD

**Issue by ebfe** [golang/gddo#275]
The index at godoc.org/-/index contains a lot of zero width spaces (`&#8203` /
`\u200b`) that don't seem to belong there. Most of them are inside the import
paths directly following a `/`, which breaks copy and pasting them.

A few examples:

```<a href="/bazil.org/bazil/cliutil/subcommands/test/calc/sum">bazil.org/&#8203;bazil/&#8203;cliutil/&#8203;subcommands/&#8203;test/&#8203;calc/&#8203;sum</a> ```

```<a href="/bitbucket.org/binet/go-clang/cmd/go-clang-dump">bitbucket.org/&#8203;binet/&#8203;go-clang/&#8203;cmd/&#8203;go-clang-dump</a>```

```<a href="/github.com/BurntSushi/toml/cmd/toml-test-decoder">github.com/&#8203;BurntSushi/&#8203;toml/&#8203;cmd/&#8203;toml-test-decoder</a>```

**Comment by ebfe** [comment]
Apparently this is on purpose: https://github.com/golang/gddo/blob/master/gddo-server/template.go#L261

**Comment by garyburd** [comment]
The spaces prevent long paths from making the table very wide.  A possible improvement is to add the spaces only when the path is longer than some length.

**Comment by shurcooL** [comment]
I was going to suggest another possible improvement to use `user-select` css property to make the invisible whitespace not selectable so it wouldn't end up being copied to clipboard, but unfortunately that css property doesn't work the same in all browsers (see details [here](https://css-tricks.com/almanac/properties/u/user-select/)).
