### ISSUE TITLE
go-talks.appspot.com is outdated

### ISSUE THREAD

**Issue by AlekSi** [golang/gddo#280]
For example, http://go-talks.appspot.com contains link to https://github.com/garyburd/talksapp/issues/new (404), but source in this repository doesn't.

**Comment by garyburd** [comment]
Yup.  And lintapp.  I sent email requesting a redeploy to the service admin.

**Comment by adg** [comment]
cc @campoy

**Comment by campoy** [comment]
Fixed now

**Comment by garyburd** [comment]
@campoy: go-lint.appspot.com should also be updated.

**Comment by campoy** [comment]
I'm not a manager of that app, could you add me? thanks

**Comment by garyburd** [comment]
Uh oh. I added you a long time ago and removed myself.

**Comment by campoy** [comment]
done
