### ISSUE TITLE
go-lint.appspot.com: "Error accessing api.github.com." for any github.com/... package.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#285]
It currently does not work for any `github.com/...` import path.

It looks like maybe it was deployed without GitHub credentials set, do you think that's it @campoy?

It's also possible it went over its rate limit quota.

![image](https://cloud.githubusercontent.com/assets/1924134/8509542/9719a46c-225d-11e5-8dd9-7760f71fb9ee.png)

**Comment by adg** [comment]
cc @campoy

**Comment by campoy** [comment]
Ooops, indeed I missed the credentials. I'll send a CL to make this error more obvious when deploying.

Thanks
