### ISSUE TITLE
Internal server error with gopkg.in/pivo.v2

### ISSUE THREAD

**Issue by jseun** [golang/gddo#286]
Godoc.org cannot show documentation for gopkg.in/pivo.v2 package. It works for gopkg.in/pivo.v1 though.  Any clues?

**Comment by jseun** [comment]
Sometime, `Error getting package files from gopkg.in.` is returned.  However, `go get gopkg.in/pivo.v2` works fine.

**Comment by garyburd** [comment]
This page http://godoc.org/gopkg.in/garyburd/redigo.v0/redis also reports internal server error. I expect it to redirect to http://godoc.org/github.com/garyburd/redigo/redis.

**Comment by Merovius** [comment]
http://godoc.org/golang.org/x/tools is also an internal server error :)

**Comment by crawshaw** [comment]
I managed to bring up a local copy of gddo. With a fresh database, all of the the packages mentioned in this bug work. So I suspect some kind of database corruption.

@adg @campoy if you can get me access to the server I can take a look.

**Comment by shurcooL** [comment]
It might also be some permissions problem.

Clearing database should be a last resort, as it'd lose an index of all Go packages, and their imports/importers relationships.

**Comment by crawshaw** [comment]
I'm not proposing dropping the database, just that the code in this repository works and whatever is wrong with godoc.org can only be fixed by someone with access to it.

**Comment by garyburd** [comment]
Somebody needs to look at the logs to see what's going on. 

I suspect that the server is out of disk space.

**Comment by jjeffery** [comment]
I am having the same issue. The URL that is failing for me is [http://godoc.org/gopkg.in/stomp.v2](http://godoc.org/gopkg.in/stomp.v2).

Something interesting about this is that the URL that points to the same code without redirection from `gopkg.in` works fine [http://godoc.org/github.com/go-stomp/stomp](http://godoc.org/github.com/go-stomp/stomp).

**Comment by crawshaw** [comment]
FYI this is a full disk. Waiting on @adg before I go deleting random files.

**Comment by adg** [comment]
Clearing out the disk. At least this time it took a long time to fill up.

**Comment by adg** [comment]
Still rm'ing files, but stuff seems to be working again.
