### ISSUE TITLE
go-talks does not understand spaces in URLs

### ISSUE THREAD

**Issue by dvyukov** [golang/gddo#293]
I uploaded my slides here:
https://github.com/dvyukov/2015-talks/tree/master/Dmitry%20Vyukov%20-%20Go%20Dynamic%20Tools

And tried to open them using go-talks as:
http://go-talks.appspot.com/github.com/dvyukov/2015-talks/Dmitry%20Vyukov%20-%20Go%20Dynamic%20Tools/tools.slide

But that did not work, go-talks says "Not Found".

Then I uploaded them to a path without spaces:
https://github.com/dvyukov/2015-talks/tree/master/Dmitry_Vyukov_-_Go_Dynamic_Tools

And that worked:
http://go-talks.appspot.com/github.com/dvyukov/2015-talks/Dmitry_Vyukov_-_Go_Dynamic_Tools/tools.slide

Presumably go-talks does not understand URL-endcoded %20 spaces and probably other special characters. It should. It sucks to reupload slides to two different locations.

**Comment by adg** [comment]
cc @campoy
