### ISSUE TITLE
Linked example should automatically be expanded

### ISSUE THREAD

**Issue by alexcesaro** [golang/gddo#295]
Linking to an example is currently a bit awkward: http://godoc.org/github.com/kr/beanstalk#example-package

It would be nice if this kind of link automatically expanded the example, as it is done with godoc: http://golang.org/pkg/archive/tar/#example_

I can do a PR if needed.

**Comment by garyburd** [comment]
Oops, [the computation of the example element id](https://github.com/golang/gddo/blob/b2e0a1be3b064d1776c2100a8f93266301464acd/gddo-server/assets/site.js#L75) was accidentally deleted in 16db97b87f4d63101b1a5b44bc2c22cb1daaa30d.

**Comment by alexcesaro** [comment]
How often is gddo deployed to production? This fix is not in production yet.
