### ISSUE TITLE
Field & function comments are low contrast and hard to read

### ISSUE THREAD

**Issue by natefinch** [golang/gddo#297]
In many packages, comments on struct fields and interface fields can get quite long, for example http://godoc.org/golang.org/x/net/context#Context - but the current stylesheets make the comments a real strain to read, even for someone with good eyesight.. the dark gray on light gray is a beast to read for any length of time.

This feels like a case where form is overriding function.  First and foremost, the text of godoc must be legible.

I suggest lightening the background of comments (&lt;pre&gt; blocks), and darkening the text inside them in order to increase contrast and make them easier to read.  

In some trials in my browser, lightening the backround on &lt;pre&gt; blocks from #f5f5f5 to #FAFAFA made a big difference.  Darkening the main text to real black (#000) and darkening the comments to rgb(85,85,85) (#555555) makes the comments much more legible, while still being slightly distinguishable from the non-comments by brightness (though the fact that they're preceded by // should be more than enough).  The lightened &lt;pre&gt; background was still very easy to distinguish from non-pre blocks.

I can submit a PR if the powers that be think it is worthwhile.

**Here's a screen shot of current godoc.org:**
![godoc-orig](https://cloud.githubusercontent.com/assets/3185864/8973886/ce5fbea4-3638-11e5-8ffc-ed4f4ec9b482.png)

**And here it is with my suggested changes:**
![godoc-mod](https://cloud.githubusercontent.com/assets/3185864/8973890/d7a4714e-3638-11e5-8e9a-7b763dbd2324.png)

**Comment by shurcooL** [comment]
In general, I am in favor of increasing contrast, the docs should be readable. In fact, docs are more important than code on godoc.org, so I'm not sure why gray is used at all (to me, gray indicates "less important than other stuff which has higher contrast against background). I would've picked green. E.g., see http://gotools.org/golang.org/x/net/context#Context. Even golang.org uses green, e.g. https://golang.org/pkg/net/#Dialer.

Now, specifically to the two images you've posted, this may be subjective (it depends on my eyes and my monitor's hardware and color profile being used):

In the second screenshot titled "suggested changes", I see that the background is made lighter (which I think is good), but the code also became lighter gray, closer to the gray of comments, making code and documents even **less** distinguishable than in the original screenshot. Is that intentional?

**Comment by shurcooL** [comment]
Also, the current godoc.org looks quite different (much more legible) than the screenshot you posted, when I look at the two side by side:

![image](https://cloud.githubusercontent.com/assets/1924134/8974570/2a0fb378-3628-11e5-922a-cdf92e017403.png)

**Comment by adg** [comment]
Here's how it looks to me:

![screen shot 2015-07-30 at 12 30 51 pm](https://cloud.githubusercontent.com/assets/8446613/8974584/d832c27c-36b6-11e5-892a-04cab99fd08b.png)

Which is illegible.

I would prefer to make the `pre` text `black` and the `.com` text `#666`. That seems like a dramatic improvement:

![screen shot 2015-07-30 at 12 33 40 pm](https://cloud.githubusercontent.com/assets/8446613/8974621/3a4eafde-36b7-11e5-910e-5c197f73c8ec.png)

**Comment by natefinch** [comment]
I think this may be a difference of browsers - I'm on Chrome on Linux... seems like your fonts are drawn more thickly than mine are.  That may be why the current CSS seems fine to the creators.

As for making the non-comment text lighter, I think it's an optical illusion - they're not actually different.  I'm fine with a dark green, just didn't want to go too crazy.

**Comment by natefinch** [comment]
FWIW, here's how it looks in Firefox on my machine: (again, on Linux, in case that matters)
![godoc-firefox](https://cloud.githubusercontent.com/assets/3185864/8984181/f615c26c-369d-11e5-8f3e-c4d355feaf9f.png)

**Comment by adg** [comment]
Anyone want to send a change to improve this? @shurcooL ?

**Comment by shurcooL** [comment]
Sure.

Any objections if I change comment color to simply be like on golang.org? Clearly golang.org has a good scheme (if it weren't, it should be changed) and I don't see why godoc.org should invent its own different one.

![image](https://cloud.githubusercontent.com/assets/1924134/9698454/0d197838-536c-11e5-9e6a-6bd7ccf19c1e.png)

**Comment by shurcooL** [comment]
@natefinch, once the change of #311 has been deployed, can you post a followup screenshot on your setup? I hope it will work nicely.

**Comment by adg** [comment]
It's deployed

**Comment by shurcooL** [comment]
FWIW, it looks absolutely beautiful to me, especially on a Retina screen. I love that now all 3 sites golang.org, godoc.org and gotools.org display comments in a consistent way. :D

![image](http://virtivia.com:27080/7ntobfbzo051.png)

**Comment by adg** [comment]
Me too. Nice work :-)

**Comment by natefinch** [comment]
Looks awesome, thanks!

![image](https://cloud.githubusercontent.com/assets/3185864/9805930/b56f20c4-580c-11e5-8b8c-bec8616fb643.png)

(Though I am jealous of the thicker fonts you guys are getting... wonder if I can tweak my Chrome settings to replicate it.)

**Comment by shurcooL** [comment]
Glad to hear!

About the thicker font, I am guessing it's using a different font for you.

According to chrome inspector, the font-family for `pre` elements comes from bootstrap, and it has Menlo as the first option, which my OS definitely has (I'm on OS X). I'm guessing that font isn't available on Linux so it's falling back to another one, which is thinner (possibly Courier New).

![image](https://cloud.githubusercontent.com/assets/1924134/9806168/327bad6a-57f6-11e5-93be-d19749b34591.png)

**Comment by natefinch** [comment]
You're right, it was defaulting down to Courier New, which is terrible.  Installed menlo, now it looks twice as slick.  Thanks!
