### ISSUE TITLE
Document discrepancy between api package list and user-facing index in API docs

### ISSUE THREAD

**Issue by stapelberg** [golang/gddo#302]
In the chrome developer tools on https://godoc.org/-/index, I used:

```javascript
var links = document.getElementsByTagName('a');
for (i = 0; i < links.length; i++) { console.log(links[i].href); }
```

Then right-clicked, save as /tmp/godoc-web-index.log, remove the first and last links which are not actually Go package names.

```shell
wget http://api.godoc.org/packages
jq '.results[].path' < packages | sort | uniq | sed 's,^"\([^"]*\)"$,https://\1,g' > /tmp/packages-from-api
sed 's,https://godoc.org/,https://,g' /tmp/godoc-web-index.log > /tmp/packages-from-index
```

Looking at the numbers, they are significantly different:

```
$ wc -l /tmp/packages-from-*
 121998 /tmp/packages-from-api
  85077 /tmp/packages-from-index
```

Here are a couple of differences:

```
colordiff -u /tmp/packages-from-{api,index} | head -20
--- /tmp/packages-from-api      2015-08-13 19:19:25.507249368 +0200
+++ /tmp/packages-from-index    2015-08-13 19:20:14.138621848 +0200
@@ -4,18 +4,14 @@
 https://0f.io/i2c
 https://0f.io/mjpeg
 https://0f.io/roomba
-https://0f.io/roomba/roombaweb
 https://0f.io/webcam
 https://0f.io/webcam/webcam
 https://9fans.net/go/acme
+https://9fans.net/go/acme/Watch
 https://9fans.net/go/acme/acmego
-https://9fans.net/go/acme/Dict
 https://9fans.net/go/acme/editinacme
-https://9fans.net/go/acme/Watch
 https://9fans.net/go/draw
 https://9fans.net/go/draw/drawfcall
-https://9fans.net/go/games/4s
-https://9fans.net/go/games/spacewar
 https://9fans.net/go/games/spacewar/pdp1
```

I wonder why some packages are only in one, but not the other? Is this expected?

**Comment by garyburd** [comment]
The API returns all packages known to godoc.org.

Internal packages, vendored packages and packages with errors are not included on the index page. 

Commands were not included on the index page in the past. A change was made to include commands, but they will not show up until the command is crawled again.

**Comment by stapelberg** [comment]
Thanks for the clarification. Perhaps this could be mentioned in the API docs and/or on the index page? :)

**Comment by adg** [comment]
Agree that the right place to mention this is in the API docs.

**Comment by garyburd** [comment]
I updated the updated the API description at https://github.com/golang/gddo/wiki/API.  Please review the change.

**Comment by adg** [comment]
LGTM thanks.

**Comment by stapelberg** [comment]
Thanks for updating the API docs. Currently, they read:

> api.godoc.org/packages—Returns all packages, in JSON format. The godoc.org/-/index page shows a subset of the packages. This API returns all packages.

Perhaps we could be a bit more specific about “subset”? e.g.: The godoc.org/-/index page shows a subset of the packages, excluding e.g. internal or vendored packages.
