### ISSUE TITLE
appengine datastore saving and loading custom Propertylists. Problem with project parameter and datastore.indexValue

### ISSUE THREAD

**Issue by Deshain86** [golang/gddo#303]
I would like to propose changing visibility of datastore.indexValue struct that is defined in file load.go. When I tried to write my own PropertyLoadSaver functions i could not access value of datastore.Property variable if in query I used "Project" feature. Instead I received  datastore.indexValue from which i could not extricate real value in which I was interested in. 

For better visualization of the issue, here is my real life example:
```go
type Entity map[string]interface{}
func (d *Entity) Load(ch []datastore.Property) error {
    x := *d
    for _, p := range ch {
        x[p.Name] = p.Value
    }
    return nil
}
```
It worked good enough when I didn't use query.Project, then this function became unreliable. If datastore.indexValue and it's Value property was globally visible i could do something like this:

```go
func (d *Entity) Load(ch []datastore.Property) error {
    x := *d
    for _, p := range ch {
        if reflect.TypeOf(p.Value) == reflect.TypeOf(datastore.IndexValue{}) && reflect.ValueOf(p.Value).Kind() == reflect.Struct {
            y := p.Value.(datastore.IndexValue).Value
            switch {
            case y.Int64Value != nil:
                x[p.Name] = y.GetInt64Value()
            case y.Pointvalue != nil:
                point := y.GetPointvalue()
                x[p.Name] = appengine.GeoPoint{Lat: point.GetX(), Lng: point.GetY()}
            case y.StringValue != nil:
                x[p.Name] = y.GetStringValue()
            case y.BooleanValue != nil:
                x[p.Name] = y.GetBooleanValue()
           case y.DoubleValue != nil:
                x[p.Name] = y.GetDoubleValue()
            }
        } else {
            x[p.Name] = p.Value
        }
    }
    return nil
}
```

**Comment by dsymonds** [comment]
This is not the place for App Engine bugs/feature requests. Try https://code.google.com/p/googleappengine/.
