### ISSUE TITLE
Make godoc.org HTTPS-only

### ISSUE THREAD

**Issue by jleclanche** [golang/gddo#304]
Is there a reason why http://godoc.org doesn't 301 to the https version? SSL is set up and works perfectly, seems like an easy fix.

**Comment by jleclanche** [comment]
Had I noticed a few days earlier I could've filed a nicely self-referential issue there...

**Comment by shurcooL** [comment]
Sounds like a good idea.

**Comment by shurcooL** [comment]
> Had I noticed a few days earlier I could've filed a nicely self-referential issue there...

Haha, just got it. :grinning:

**Comment by adg** [comment]
We'd want to set up HSTS in the SSL cert also.

**Comment by adg** [comment]
Should be pretty easy to do the server-side part of this with a change similar to this one: https://github.com/golang/tools/commit/40b1b219defb04ecd3f7b32bac7e6d0c5ebbe89c#diff-871153e4ac7a351c1a6c61e5013b51c8R36
