### ISSUE TITLE
godoc.org shows outdated 1.4 docs for standard Go packages (instead of 1.5).

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#305]
This also means some new 1.5 Go packages are missing, etc.

Go 1.5 is the current latest stable release.

I use godoc.org for all my look-up-Go-doc needs and having 1.5 docs will be very appreciated. I have to revert to using golang.org/pkg until this is resolved, which is a longer url, doesn't support 3rd party import paths, and doesn't have find symbol functionality (accessible via `F` keyboard shortcut).

Thanks!

**Comment by garyburd** [comment]
Can you give specific examples of missing or outdated docs?  The pages I checked are up to date.

**Comment by shurcooL** [comment]
Sorry about that false information!

The issue I found was that new Go 1.5 packages were missing, and I incorrectly assumed that it was simply because docs were still on 1.4. The one rare time I made an assumption and it was wrong. Sorry, I should've verified before stating that.

Thanks for making a PR to resolve the issue so quickly!
