### ISSUE TITLE
Remove playground links for code outside the standard library

### ISSUE THREAD

**Issue by razrman** [golang/gddo#308]
The example 'Play' for the image package Play is broken.

https://godoc.org/golang.org/x/image/draw?play=Draw
 
![golangdrawexampleplayerror](https://cloud.githubusercontent.com/assets/1226040/9549049/db5383d4-4d58-11e5-9016-6b1655955591.PNG)
godoc page for the image package.

**Comment by garyburd** [comment]
The play link sets the false expectation that the example will run. I propose that we remove the play link for examples outside of the standard library.
