### ISSUE TITLE
godoc intermittent 'internal server error'

### ISSUE THREAD

**Issue by razrman** [golang/gddo#309]
If I repeat the following sequence of clicks in Chrome I occasionally get 'internal server error'

https://godoc.org/golang.org/x/image/draw#example-Draw

https://godoc.org/golang.org/x/image/draw#ex-Draw

https://godoc.org/golang.org/x/image/draw#ex-Draw

https://godoc.org/golang.org/x/image/draw?play=Draw

![godocinternalservererror](https://cloud.githubusercontent.com/assets/1226040/9549360/83d58a74-4d5a-11e5-9260-186e3e4aa3d7.PNG)

**Comment by adg** [comment]
There are occasionally production issues, but this issue is now too old to help us track them down, so I'm closing it. Thanks for the report.
