### ISSUE TITLE
Highlight destination identifier on in-page navigation

### ISSUE THREAD

**Issue by wallclockbuilder** [golang/gddo#310]
Selecting a function only works on small screens.
Heres what I mean:

When I click on a function. 
![screen shot 2015-09-02 at 9 39 30 am](https://cloud.githubusercontent.com/assets/2033945/9628310/7d6d4368-5159-11e5-94bf-923d7794d7f2.png)

The godoc page takes me to that function's section. However the function I'm looking for is lost among the other functions. 
![screen shot 2015-09-02 at 9 34 12 am](https://cloud.githubusercontent.com/assets/2033945/9628319/929ad20a-5159-11e5-9028-17463bc9ee23.png)

This can be improved by making the selected function stand out.
![screen shot 2015-09-02 at 9 37 23 am](https://cloud.githubusercontent.com/assets/2033945/9628336/aa82a8ac-5159-11e5-9582-a416dcfc02ec.png)

**Comment by shurcooL** [comment]
It tries to put the function at the top of the screen, but can't because the page is too short/your browser window is tall.

So this only affects things in the bottom-most area as tall as your window.

I agree it can be improved though.

**Comment by wallclockbuilder** [comment]
You're right. It tries to put the function at the top of the screen. That usually works until it doesn't, then I get this very painful confusion because the function is supposed to be at the top of the screen but its not there. That totally destroys my flow. Its not a pleasant experience. The UX should be consistent. This is broken.

Highlighting the selected function makes the experience consistent.

**Comment by adg** [comment]
I think the solution here is to add some javascript to highlight the target identifier on navigation. Should be pretty straightforward.

**Comment by nickrobinson** [comment]
Taking a look at this

**Comment by nickrobinson** [comment]
Submitted a Pull Request https://github.com/golang/gddo/pull/328

**Comment by wallclockbuilder** [comment]
ok Thanks.

**Comment by lucidlime** [comment]
Should this be closed or is there more to do?
