### ISSUE TITLE
Comments on interface methods displayed as source code

### ISSUE THREAD

**Issue by meling** [golang/gddo#313]
The following section does not appear to have been processed properly by godoc:
http://godoc.org/golang.org/x/net/context#Context

(Haven't check if this applies to other similar interface doc comments.)

**Comment by garyburd** [comment]
Interfaces are displayed as code using the godoc tool and godoc.org.

Issue https://github.com/golang/go/issues/5860 asks that interface methods be displayed like other methods.

**Comment by adg** [comment]
Will close until there's an obvious way to address this.
