### ISSUE TITLE
No obvious way to go get to source code

### ISSUE THREAD

**Issue by adg** [golang/gddo#314]
See golang/go#12676

**Comment by garyburd** [comment]
The link on the [Package Files](http://godoc.org/github.com/gorilla/websocket#pkg-files) header is subtle.

I propose that we:
- Remove the link from the header.
- Add text below the header:

     The package source code hosted on [github.com](https://github.com/gorilla/websocket).

**Comment by techtonik** [comment]
No need to add text. Just move package files before API.

**Comment by adg** [comment]
I agree visibility should be improved for package sources, but I believe it is much worse for commands. For example: http://godoc.org/github.com/golang/lint/golint

Would this change address commands too?

**Comment by garyburd** [comment]
@techtonik The file section follows the index section for consistency with the godoc command.

@adg How about adding a files section to the bottom of command pages?

**Comment by adg** [comment]
@garyburd I'd be happy with that.

**Comment by techtonik** [comment]
> The file section follows the index section for consistency with the godoc command.

Why this consistency is needed? Especially if it hurts usability.

Comments from https://github.com/golang/go/issues/12676#issuecomment-142843443:

1. ` Index | Files ` look excessive - better replace it with ` Issues | Code ` there
2. `Package Files` and `Files` are not consistent
3. `Package Files` and `Index` headers are not consistent
4. `Package Files` is buried under API index

Files are better be sorted in a column. `Directories` also look strange disconnected from `Files`.

I propose the following structure.

`Brief` | `Examples` | `API` | `Source code`

`Source code` has `Files` and `Directories` subsections.
