### ISSUE TITLE
Dockerfile fails to build due to bad link

### ISSUE THREAD

**Issue by nickrobinson** [golang/gddo#326]
The link to https://snappy-go.googlecode.com/archive/12e4b4183793ac4b061921e7980845e750679fd0.tar.gz in the Dockerfile does not resolve at the moment which is leading to the Dockerfile failing to build. Anyone have another source for this file?

**Comment by adg** [comment]
The `snappy` package now lives in https://github.com/golang/snappy

**Comment by fiorix** [comment]
Hey @nickrobinson patch has been merged, please close this one.
