### ISSUE TITLE
Repo has disappeared and won't auto-import on godoc.org

### ISSUE THREAD

**Issue by nathanjsweet** [golang/gddo#332]
[My spellcheck respository](https://github.com/nathanjsweet/gohun) was removed from godoc.org, and when I try searching for it, it won't auto-import it. Any thoughts?

**Comment by adg** [comment]
Hm, when I load [the godoc page] I see this in the logs:
```
2015/10/07 03:21:47 web   fetch: 480 notfound: no Go files or subdirs github.com/nathanjsweet/gohun
```
Not sure why this is happening, as there does appear to be Go source code in that repo. Did you change anything around the same time as it became delisted?

**Comment by nathanjsweet** [comment]
Yeah, a little:
- I changed main.go to use the CGO ${SRCDIR} feature that's new to 1.5+, moving away from pkg-config. 
- I changed the makefile, as it didn't have as much work to do (creating the pkg-config file, etc).

Other than those two things I can't think of anything, other than fixing a typo I found in the doc.go file.

**Comment by adg** [comment]
I cloned your repo and observed the same "Not found" error for godoc.org on
that repo.

Then I [deleted all go files except doc.go](
https://github.com/adg/gohun/commit/c28d0758d3418611bd01cc23864ec14ee1e406e0)
and the [documentation reappeared](https://godoc.org/github.com/adg/gohun).

I restored the _test.go file and it still worked. So, something about the
contents of gohun.go is tricking godoc.org into thinking the package
doesn't exist.

**Comment by nathanjsweet** [comment]
Well, I think that the site isn't handling the new ${SRCDIR} directive very well. Try using [this gohun.go](https://raw.githubusercontent.com/nathanjsweet/gohun/2929e8a0d9e1f60186385e7c9611b876566376e7/gohun.go), to see if it works.

**Comment by adg** [comment]
I don't see why it should care about the SRCDIR directive. It shouldn't be
parsing cgo comments at all.

**Comment by nathanjsweet** [comment]
Well, unfortunately, it seems to be the case, because [I took it out](https://github.com/nathanjsweet/gohun/commit/a355e96dd2252b578500de8ee7ed2b1efa2e7fbc) and now [its working](https://godoc.org/github.com/nathanjsweet/gohun).
>I don't see why it should care about the SRCDIR directive. It shouldn't be
parsing cgo comments at all.

**Comment by nathanjsweet** [comment]
My guess is that the dollar sign and or brackets are throwing it off.

**Comment by nathanjsweet** [comment]
>I don't see why it should care about the SRCDIR directive. It shouldn't be
parsing cgo comments at all.

[Builder.go](https://github.com/golang/gddo/blob/master/doc/builder.go) does seem to care.

**Comment by nathanjsweet** [comment]
FYI, I reverted my repo, so that it's not broken. It no longer is in godoc.org, as before.

**Comment by garyburd** [comment]
The server running on my Linux desktop can load the package. I built the server with Go 1.5.1. Hmmm.

**Comment by nathanjsweet** [comment]
I'm guessing that 1.5 is currently not in use on the live site? That would be my guess.

**Comment by garyburd** [comment]
Yup, breaks on 1.4. I submitted #333 to help diagnose problems like this the future.

@adg Please build with 1.5.1.

**Comment by adg** [comment]
Updated to 1.5.1. Now it works.

**Comment by nathanjsweet** [comment]
Thanks.
