### ISSUE TITLE
GitHub regexp doesn't match nested directories

### ISSUE THREAD

**Issue by MihaiB** [golang/gddo#340]
https://godoc.org/github.com/golang/gddo/httputil/header
fails with this error in the logs:
`web   fetch: 0 notfound: Import path prefix matches known service, but regexp does not. github.com/golang/gddo/httputil/header`

https://godoc.org/github.com/golang/gddo/httputil works.

I've pinpointed this to 43f88a7eb784b97bc9c4eaed7ce286d99773fc87 which inadvertently made the github regexp match at most 1 directory deep.

**Comment by adg** [comment]
@MihaiB thanks very much for the fix. It is now deployed and the issue appears to be resolved. :-)
