### ISSUE TITLE
there is no (* Logger)SetOutput function in golang log package in 1.4.2 ,but there still has a information about that function on the page which url is 'https://godoc.org/log' 

### ISSUE THREAD

**Issue by luckykris** [golang/gddo#344]
there is no (* Logger)SetOutput function  in golang log package  in 1.4.2 ,but  there still has a information about that function  on the page  which url is 'https://godoc.org/log'

**Comment by adg** [comment]
Can you please provide more information? It's not clear what you're reporting here.

**Comment by luckykris** [comment]
sorry ,my english is terrible  ,  i had rewrite  my comment . i thought it may clear about  the issue.

**Comment by shurcooL** [comment]
godoc.org only shows the documentation for the latest stable release of Go, which is 1.5.1 at this time.
