### ISSUE TITLE
Internal server error at https://godoc.org/github.com/golang/go/src/cmd/vet/doc.go

### ISSUE THREAD

**Issue by twotwotwo** [golang/gddo#345]
https://godoc.org/github.com/golang/go/src/cmd/vet referred me to doc.go, so I tried https://godoc.org/github.com/golang/go/src/cmd/vet/doc.go on the off-chance that might work. It did not, which is fine, but I got an "Internal server error" response, so perhaps something is panicking instead of presenting a 404.

**Comment by shurcooL** [comment]
Can confirm. It should be displaying a 404 Not Found like you see when you visit https://godoc.org/github.com/golang/go/src/cmd/vet/docgo or so.
