### ISSUE TITLE
NewRediStore description is same as the NewCookieStore's

### ISSUE THREAD

**Issue by Running-Snail** [golang/gddo#349]
the func NewRediStore's description in martini sessions doc page is same as the NewCookieStore's description
the doc link
https://godoc.org/github.com/martini-contrib/sessions

**Comment by shurcooL** [comment]
That's what the actual code of that package has:

https://github.com/martini-contrib/sessions/blob/fa13114fbcf036dff8185d728651d85fcef772db/redis_store.go#L19-L30

This issue belongs in that project's issue tracker:

https://github.com/martini-contrib/sessions/issues

**Comment by shurcooL** [comment]
Closing because it's not an issue in gddo project.
