### ISSUE TITLE
Refreshing gopkg.in packages doesn't work

### ISSUE THREAD

**Issue by alexcesaro** [golang/gddo#358]
Refreshing the documentation of a gopkg.in package doesn't work and gives the following error: `Error refreshing package: Error getting package files from gopkg.in`.

I first thought the bug was on gopkg.in side so I opened an issue [there](https://github.com/niemeyer/gopkg/issues/40). But the bug might be on GoDoc side and even if it is a gopkg.in bug some details on what is causing the bug could help fixing it. That's why I'm also opening that issue.

**Comment by shurcooL** [comment]
From your linked issue, you said you had a problem with refreshing this package (and another, but I'll use this one for testing):

https://godoc.org/gopkg.in/gomail.v2

I confirm trying to refresh that package gives an internal server error right now.

I've tried refreshing it on https://gotools.org/gopkg.in/gomail.v2 and it worked without issues there. So I'm guessing it's likely an issue on godoc.prg side.

I won't be able to look into this in more detail until later.

**Comment by elithrar** [comment]
I can't replicate this either. It may have been during a period of gddo instability/downtime.

**Comment by alexcesaro** [comment]
Yes I don't know what changed but it looks like it is working now.
