### ISSUE TITLE
I am not able to add my repository

### ISSUE THREAD

**Issue by mouadino** [golang/gddo#359]
Why I can't add my repository here github.com/mouadino/go-nano ? I tried both to search using "go-nano" and "github.com/mouadino/go-nano", none of them works :(

> To add a package to GoDoc, search for the package by import path. If GoDoc does not already have 
> the documentation for the package, then GoDoc will fetch the source from the version control system 
> on the fly and add the documentation.

I am sorry to say, but IMHO this way of building docs is not user friendly, can you maybe add a doc builder status ?

**Comment by broady** [comment]
`github.com/mouadino/go-nano` doesn't contain any `.go` files. I just browsed to a subpath, and it works perfectly:
https://godoc.org/github.com/mouadino/go-nano/utils

**Comment by mouadino** [comment]
@broady now it's look like godoc know about it :) not sure why thou ? did you by any chance trigger build by searching by another keywords ? if that the case maybe a docu need change ?

Closing this issue since my problem is solved

**Comment by broady** [comment]
All I did was visit this the `go-nano/utils` package link I pasted above.

Maybe the docs need a change, but it already looks correct. `github.com/mouadino/go-nano` itself isn't a Go package (it has no Go files).

**Comment by mouadino** [comment]
@broady good to know, thank you by the way :)
