### ISSUE TITLE
no way to jump to files

### ISSUE THREAD

**Issue by bradfitz** [golang/gddo#360]
How do I get from this page to its files?

https://godoc.org/golang.org/x/build/cmd/release

There's no link.

**Comment by shurcooL** [comment]
I usually achieve that by replacing "doc" with "tools" in the URL, but I don't think that's a satisfactory general solution.

**Comment by lstokeworth** [comment]
Dup of https://github.com/golang/gddo/issues/314 ?

**Comment by lucidlime** [comment]
Fixed by c26cf282860290b7d2c69c49cc1c4bf4bed6691b
