### ISSUE TITLE
Internal Server Error <Jan, 07 2016>

### ISSUE THREAD

**Issue by logrusorgru** [golang/gddo#364]
Hi, I've got the Internal Server Error on each page except home, and about.

I want to note that `godoc.org` much more convenient than `golang.org/pkg/...` And I would not like to abandon it.

Thank you.

**Comment by etelej** [comment]
![godoc](https://cloud.githubusercontent.com/assets/2271973/12171770/89b8d188-b55d-11e5-9ddf-68f2c976b9f9.JPG)
Yeah, seems to have an issue

**Comment by loapsw** [comment]
Will it go on long?

**Comment by 1l0** [comment]
Relax. Just use offline doc for a while.

**Comment by petemoore** [comment]
I think it has been down for at least 8 hours now, (at a guess) - I've been trying all day - don't remember exactly when I first noticed.

**Comment by wallclockbuilder** [comment]
In the mean time feel free to use https://gowalker.org.
Working for me https://gowalker.org/github.com/btcsuite/btcd/txscript#SigCache

**Comment by dsoprea** [comment]
+1

**Comment by sebastianbroekhoven** [comment]
[+1]

**Comment by logrusorgru** [comment]
> In the mean time feel free to use https://gowalker.org.

**Comment by logrusorgru** [comment]
Oh, hell. I clicked the wrong button. Sorry.

> In the mean time feel free to use https://gowalker.org.

Yeah, it is a good one.

**Comment by hnsl** [comment]
Same here. Whole site is down. :(

**Comment by martinpinto** [comment]
Yeah it's still down

**Comment by adg** [comment]
Taking a look

**Comment by adg** [comment]
It's back, sorry for the inconvenience.
Now working on solving the underlying issues to prevent this from occurring again.

**Comment by hnsl** [comment]
Thanks @adg!
