### ISSUE TITLE
search: seems to ignore path name as argument to search

### ISSUE THREAD

**Issue by robpike** [golang/gddo#384]
If I do a godoc.org search for

    acme/Watch

it doesn't find 9fans.net/go/acme/Watch, which it should.
On the other hand a search for

   Watcher

does find it, which is good but peculiar.

**Comment by shurcooL** [comment]
I agree with the above being a problem, and it can be improved.

A related search issue that was opened somewhat recently is:

#366

There have been many more search-related issues raised, but so far they have not been resolved:

https://github.com/golang/gddo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+search+in%3Atitle+

**Comment by adg** [comment]
@shantuo this might be a good issue to start with when looking to improve the search.

**Comment by shantuo** [comment]
I'm working on this issue as well as #366
