### ISSUE TITLE
there is no bugs link for package pages

### ISSUE THREAD

**Issue by kortschak** [golang/gddo#387]
1. What did you do?
Browse to https://godoc.org/encoding/xml and compare with https://golang.org/pkg/encoding/xml/

2. What did you expect to see?
A link reasonably high up on the page linking to the single BUG section.

3. What did you see instead?
No link.

It would be nice to either reflect the behaviour of golang.org/pkg, or IMO preferably have a link next to "Index | Examples | Files".

**Comment by adg** [comment]
Thanks for reporting it here.
