### ISSUE TITLE
talksapp: Internal Server Error when viewing a seemingly valid/existing .slide file.

### ISSUE THREAD

**Issue by kpurdon** [golang/gddo#391]
`http://go-talks.appspot.com/github.com/kpurdon/go-presentations/http-middleware-chaining/http-middleware-chaining.slide` attempting to access this slide file I get an Internal Server Error.

**Comment by TymoteuszL** [comment]
Same for me, but there's also no article (404)
http://go-talks.appspot.com/github.com/kpurdon/go-presentations/http-middleware-chaining/http-middleware-chaining.article :)

I understand you would like to receive Not found instead of Internal server error?

**Comment by shurcooL** [comment]
The `http-middleware-chaining.slide` file does exist though:

https://github.com/kpurdon/go-presentations/tree/master/http-middleware-chaining

**Comment by kpurdon** [comment]
Let me know if any other information is needed ... not much else I can give on my end. The slide file works perfectly fine with the local present tool.

**Comment by adg** [comment]
cc @campoy

**Comment by campoy** [comment]
The problem here is that the slide refers to a file  `./snippets/01.go` that fails to be loaded in prod.

I wonder if it's related to using the `./` at the beginning of the filepath.

I'm investigating now.

**Comment by campoy** [comment]
I can confirm that the problem is related to the `./` at the beginning of the path, please remove it so you import just `snippets/01.go`.

I'll now investigate why that causes this error.

**Comment by campoy** [comment]
I was not able to make the PR [here](https://go-review.googlesource.com/c/21898/) point to this issue directly.

Any clues on how to do that, @adg?

**Comment by campoy** [comment]
Fix deployed, http://go-talks.appspot.com/github.com/kpurdon/go-presentations/http-middleware-chaining/http-middleware-chaining.slide now works

**Comment by adg** [comment]
Great, thanks!
