### ISSUE TITLE
Internal Server Error when imported file is missing

### ISSUE THREAD

**Issue by campoy** [golang/gddo#395]
The error message when a slide imports a non existing file is currently `500 Internal server error.` which doesn't help understand the user why this fails.

Change the error to be something more meaningful, maybe with a different status code.

**Comment by shurcooL** [comment]
Is this scoped to talksapp only? Or lintapp and gddo as well? I wonder what other people think of #363.

**Comment by campoy** [comment]
This is just for gddo and completely unrelated to #363.

Actually, it turns out we're already giving information when a file is missing, so closing this issue.

**Comment by shurcooL** [comment]
I see. You mentioned "when a slide imports" so I thought it was about talksapp. It's hard to tell without a prefix in the issue title.
