### ISSUE TITLE
Unable to add a project which works fine with go get.

### ISSUE THREAD

**Issue by kwilczynski** [golang/gddo#398]
Sorry to bother , but I am a little stumbled.

I have a project which (work in progress) seem to work fine with `go get` and with services like `https://goreportcard.com/`, but I cannot seem to be able to make it work with `godoc.org`, not sure what I am doing wrong to upset it.

The following is the output from running `gddo-server` locally:

```
2016/04/15 17:46:47 Starting server, os.Args=./gddo-server -db-log
2016/04/15 17:46:47 Do() -> (<nil>, <nil>)
2016/04/15 17:46:55 Do(EVALSHA, "0aff07045e4dd56c10dfecaa013c24dd"..., 0, 49) -> ([], <nil>)
2016/04/15 17:46:55 Do() -> (<nil>, <nil>)
2016/04/15 17:47:00 Do(EVALSHA, "7b1a288005ca6077e301795f57cf5259"..., 0, "github.com/kwilczynski/packer-pr"...) -> (<nil>, <nil>)
2016/04/15 17:47:00 Do(EVALSHA, "fdba98d3687114ef9e7b0e085385532a"..., 0, "github.com/kwilczynski/packer-pr"..., "github.com/kwilczynski", "github.com") -> ([], <nil>)
2016/04/15 17:47:00 Do() -> (<nil>, <nil>)
2016/04/15 17:47:00 Do(EVALSHA, "85a9ceb3fbc60423fe6d79c1c3758d0e"..., 0, "github.com/kwilczynski/packer-pr"...) -> (0, <nil>)
2016/04/15 17:47:00 Do() -> (<nil>, <nil>)
2016/04/15 17:47:02 Do(EVALSHA, "894aab5a37b24afd1154519e43ead325"..., 0, "github.com/kwilczynski/packer-pr"...) -> (<nil>, <nil>)
2016/04/15 17:47:02 Do() -> (<nil>, <nil>)
2016/04/15 17:47:02 web   fetch: 1925 notfound: No files in directory. github.com/kwilczynski/packer-provisioner-itamae-local
2016/04/15 17:47:02 Do(INCR, "maxQueryId") -> (6, <nil>)
2016/04/15 17:47:02 Send(SINTERSTORE, "tmp:query-6", "index:github.com", "index:kwilczynsk", "index:pack", "index:provid", "index:itama", "index:loc") -> (<nil>)
2016/04/15 17:47:02 Send(SORT, "tmp:query-6", "DESC", "BY", "nosort", "GET", "pkg:*->path", "GET", "pkg:*->synopsis", "GET", "pkg:*->score") -> (<nil>)
2016/04/15 17:47:02 Send(DEL, "tmp:query-6") -> (<nil>)
2016/04/15 17:47:02 Receive() -> (0, <nil>)
2016/04/15 17:47:02 Receive() -> ([], <nil>)
2016/04/15 17:47:02 Receive() -> (0, <nil>)
2016/04/15 17:47:02 Do() -> (<nil>, <nil>)
```

This would show up:

```
2016/04/15 17:47:02 web   fetch: 1925 notfound: No files in directory. github.com/kwilczynski/packer-provisioner-itamae-local
```

Does this mean that no `.go` files were found?

Result from running `go get`: 

https://gist.github.com/kwilczynski/b0cac7d05befd97975351b143f0577c1

I would really appreciate any hints on how to get it to work, anything I need to fix, etc.

Thank you!

**Comment by shantuo** [comment]
Hi @kwilczynski , godoc.org crawls github repo from master branch. You work so far is on another branch and there is nothing on master branch to be fetched.

**Comment by kwilczynski** [comment]
Hi @shantuo, thank you for getting back to me. Oh I see. I thought that I did something wrong project-structure wise assuming that since `go get` worked so should `gddo-server`. I will move code onto the master branch (nice and simple). Any plans to make it work with whatever branch is set as default in GitHub?

**Comment by shantuo** [comment]
Hi @kwilczynski , there's no plan of doing that now. The reason they decided to implement fetching in this way I think is to avoid getting projects in developing.

**Comment by kwilczynski** [comment]
@shantuo makes sense! Thank you for help! ❤️
