### ISSUE TITLE
broken links to talks.godoc.org/foo.slide

### ISSUE THREAD

**Issue by sbinet** [golang/gddo#401]
hi,

it seems the recent godoc.org update also broke the redirection from talks.godoc.org/some-repo/my-talk.slide to the underlying presenter.

this was working:
 https://talks.godoc.org/github.com/sbinet/talks/2015/20151109-gopy-dotgo/gopy-dotgo.slide

it's not now:
```
$ curl https://talks.godoc.org/github.com/sbinet/talks/2015/20151109-gopy-dotgo/gopy-dotgo.slide
curl: (35) Unknown SSL protocol error in connection to talks.godoc.org:443 
```

but this is still working:
```
$ curl http://go-talks.appspot.com/github.com/sbinet/talks/2015/20151109-gopy-dotgo/gopy-dotgo.slide | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<!DOCTYPE html>
<html>
  <head>
    <title>gopy: extend CPython with Go</title>
    <meta charset='utf-8'>
    <script src='/static/slides.js'></script>
    <script>
```

could this be fixed?

thanks,
-s

**Comment by shurcooL** [comment]
What is https://talks.godoc.org? I have never seen that url. Is it supposed to be the same as https://go-talks.appspot.com, or is it something else?

**Comment by adg** [comment]
@stephenmw does this ring any bells to you?

**Comment by sbinet** [comment]
ping?
I have a fairly large corpus of talks pointing at the "old" URL (`talks.godoc.org/...`):
 github.com/sbinet/talks
 github.com/go-hep/talks

should I just bite the bullet and migrate all the links (that are under my control) to point to `go-talks.appspot.com/...` ?

I was (perhaps naively) under the impression the `talks.godoc.org` URL would be more stable than whatever would serve the present talk underneath :)

**Comment by adg** [comment]
@stephenmw can you please take a look at this? Seems to be a breakage as a result of the recent infrastructure work.

**Comment by broady** [comment]
And if this is a domain we don't want to support but worked before, we could just set up a redirect.

**Comment by stephenmw** [comment]
Working on it. The issue is we don't have an ssl cert for talks.godoc.org but we require ssl in App Engine.

**Comment by stephenmw** [comment]
@sbinet my goal is to eventually merge  go-talks to talks.godoc.org. Please don't change that :-).

**Comment by sbinet** [comment]
@stephenmw glad to hear it :)

**Comment by stephenmw** [comment]
Done. Uploading an SSL cert was all that was needed.

**Comment by stephenmw** [comment]
As long as stuff was broken, I also took a risk and assigned talks.godoc.org to go-talks. It now works without redirects.

**Comment by sbinet** [comment]
thanks a **lot** :)
