### ISSUE TITLE
Example not showing up in the documentation output

### ISSUE THREAD

**Issue by kevinburkeshyp** [golang/gddo#403]
I've added the following code in `client_test.go`, here: https://github.com/Shyp/rickover/blob/master/downstream/client_test.go

```go
package downstream

import (
	"encoding/json"

	"github.com/Shyp/rickover/Godeps/_workspace/src/github.com/Shyp/go-types"
)

// Create a new client, then make a request to a downstream service with an
// empty data object.
func Example() {
	client := NewClient("test", "hymanrickover", "http://downstream-server.example.com")
	params := JobParams{
		Data:     json.RawMessage([]byte("{}")),
		Attempts: 3,
	}
	id, _ := types.NewPrefixUUID("job_123")
	client.Job.Post("invoice-shipment", &id, &params)
}
```

I expect that this example would show up on this page: https://godoc.org/github.com/Shyp/rickover/downstream

When I run godoc locally:

```
(sleep 1; open http://localhost:6060/pkg/github.com/Shyp/rickover) &
godoc -http=:6060
```

I can navigate to `http://localhost:6060/pkg/github.com/Shyp/rickover/downstream` and view the example:

<img src="https://monosnap.com/file/zvm5XGz7nc7tuhy3a8mJTvW9UZQ9se.png">

I've tried changing the function name from Example() to ExampleClient(), it still shows up locally, but not on `godoc.org`. I've also tried clicking "Refresh now" and just waiting (I published that doc example four hours ago), but it still seems like it's not showing up.

**Comment by shurcooL** [comment]
That is pretty unexpected, and looks like a valid issue (especially since godoc the binary displays examples). godoc.org does support examples for 3rd party packages. For example, see them working on https://godoc.org/github.com/shurcooL/github_flavored_markdown.

**Comment by jackcohen** [comment]
Is this #404 (refresh not working) instead of an issue with example?  Example is visible now: https://godoc.org/github.com/Shyp/rickover/downstream#example-package

**Comment by shurcooL** [comment]
Yeah, that's very likely.
