### ISSUE TITLE
URLs containing semicolons produce incomplete hyperlinks

### ISSUE THREAD

**Issue by mdlayher** [golang/gddo#406]
For example:

https://godoc.org/github.com/digitalocean/go-qemu/qmp#Libvirt.Run

This URL is valid, but godoc.org does not handle it properly.  I'd be happy to look into a solution for this in the next couple of days.

**Comment by normanvashon** [comment]
The bug is in go/doc. See https://play.golang.org/p/s7-kyuoQx3

**Comment by mdlayher** [comment]
Closing in favor of https://github.com/golang/go/issues/16565.
