### ISSUE TITLE
Bootstrap CDN broken, vendor bootstrap locally

### ISSUE THREAD

**Issue by SamWhited** [golang/gddo#410]
Bootstrap (and other js/css resources) should be vendored locally in case the CDN fails to work. For the last several days the bootstrap CDN has been returning invalid OCSP data, causing Firefox to refuse to load the page:

> An error occurred during a connection to maxcdn.bootstrapcdn.com. The OCSP response contains out-of-date information. Error code: SEC_ERROR_OCSP_OLD_RESPONSE

**Comment by NikonMcFly** [comment]
I think you could just used NPM installation.

**Comment by adg** [comment]
I do not want to introduce NPM as part of the maintenance of this project. It should be as simple as copying the files to the correct location in the repo and updating the script/style/etc tags in the HTML templates.

**Comment by antbbn** [comment]
I fixed this, going trough the Gerrit submission procedure right now.

**Comment by SamWhited** [comment]
@antbbn Link? I was going to spend a bit of time tackling this if you decided not too and couldn't find a Gerrit submission.

**Comment by antbbn** [comment]
Hi, the gerrit submission is here https://go-review.googlesource.com/#/c/23335/
