### ISSUE TITLE
github.com/gonum/plot/vg/draw not available

### ISSUE THREAD

**Issue by rabun788** [golang/gddo#413]
github.com/gonum/plot/vg/draw is not available and code is broken due to not being accessible.

```package github.com/gonum/plot/vg/draw/canvas.go: cannot find package "github.com/gonum/plot/vg/draw/canvas.go" in any of:
	/usr/local/go/src/github.com/gonum/plot/vg/draw/canvas.go (from $GOROOT)
	/home/vagrant/src/github.com/gonum/plot/vg/draw/canvas.go (from $GOPATH)```

**Comment by shurcooL** [comment]
This is the wrong issue tracker, it's for `github.com/golang/gddo` project, but the issue you're reporting is in `github.com/dgryski/carbonapi` project.

The issue you opened in https://github.com/dgryski/carbonapi/issues/125 looks like it's in the right place.
