### ISSUE TITLE
update Source-Code-Links Wiki

### ISSUE THREAD

**Issue by dmitris** [golang/gddo#417]
https://github.com/golang/gddo/wiki/Source-Code-Links lists several rules that `must be followed until the implementation is fixed (see #385)` - however, https://github.com/golang/gddo/issues/385 is fixed and closed, we probably should update the Wiki accordingly.

@shurcooL

**Comment by shurcooL** [comment]
Thanks for the reminder.

I've [updated](https://github.com/golang/gddo/wiki/Source-Code-Links/_compare/862152868c7710b123e4dc8e098c8fe9d1bebf5b...68e5f06c2e226b2a0b8ab9b3b92dbc0e22433c13) the wiki to reflect the changes of #385. The final solution to #385 was the simplest possible that resolved my immediate need and addressed one bullet point, but it does not resolve all of issues with the file block parsing implementation.

As I mentioned in https://github.com/golang/gddo/issues/385#issuecomment-197196088:

> I think this is the best that's possible before refactoring the entire `LineFmt` thing, which is extremely constraining. But refactoring `LineFmt` may not be easy, even `lintapp` depends on it.
