### ISSUE TITLE
.play looks broken

### ISSUE THREAD

**Issue by Deleplace** [golang/gddo#418]
Hello
I persistently get following server response when posting to `talks.godoc.org/compile` by clicking [Run] inside presentation, or with curl :
`{"compile_errors":"can't load package: package main: \nprog.go:1:1: expected 'package', found 'EOF'\n","output":""}`

**Comment by sbinet** [comment]
me too.

see this presentation, for example:
http://talks.godoc.org/github.com/sbinet/parisgo/20150417-tuto/slides/parisgo.slide#7

it works when run locally, though.

**Comment by sbinet** [comment]
(gentle) ping?

**Comment by broady** [comment]
I see `Program exited.` on that slide, so something's changed, but it's still broken.

I wonder if it's related to golang/go#16617

**Comment by sbinet** [comment]
it doesn't seem to be tightly related as I still see `Program exited`.

BTW, this new error mode (`Program exited`) resembles the one when you run `present` locally, bind to an address (say `localhost:8080`) and connect your browser to another one (say `8.8.8.8:8080`).

hth,
-s

**Comment by campoy** [comment]
The problem was solved by using HTTPS for the POST request to the playground.
I'm now investigating if this is a bug in `urlfetch` or somewhere else.

**Comment by sbinet** [comment]
thanks a lot!
(this issue can be closed, indeed)

**Comment by Deleplace** [comment]
Thanks!!
