### ISSUE TITLE
Questions about the function recursion example on the page 123 of book "the go programming language"

### ISSUE THREAD

**Issue by Almodovar** [golang/gddo#419]
I am reading the book "the go programming language" and get confused by the example on the page 123 which traverse a html document tree to illustrate the concept of function recursion. In the example, a slice "stack" is passed to the callee and the book explains that "the callee receives a copy of stack and will not modify the initial stack". Based on my understanding, slice should be a reference type and should be modified by the callee. 

Thanks in advance.

**Comment by adg** [comment]
Not the right place to ask about this. golang.org/wiki/Questions
