### ISSUE TITLE
internal server error accessing documentation

### ISSUE THREAD

**Issue by normanvashon** [golang/gddo#420]
Viewing this page https://godoc.org/github.com/bradfitz/aws results in "Internal server error."

**Comment by shurcooL** [comment]
The error is:

```
2016/07/03 14:49:48 web   fetch: 626 delete package is a quick bug-fix fork github.com/bradfitz/aws
2016/07/03 14:49:48 Error serving /github.com/bradfitz/aws: package is a quick bug-fix fork
```

Looks like it's caused by 7f31cf313c5bb23d73ce39228b4e8bde8c1cfc56.

**Comment by adg** [comment]
@shantuo I don't think these pages should be blocked from visibility, just the index. Is that right?

**Comment by shantuo** [comment]
They were removed from db. Do you think it's better to just not index them?

**Comment by adg** [comment]
Yeah, people should be able to access the docs for any package that can be
accessed by 'go get'.
But dupes etc should be removed from search indices etc.
