### ISSUE TITLE
?status.png rendering is low quality

### ISSUE THREAD

**Issue by ahmetalpbalkan** [golang/gddo#421]
The ?status.png returns images that are low quality. Here's a travis-ci.org vs godoc comparison (zoomed in with Ctrl+ a few times on Chrome browser).

> [![image](https://cloud.githubusercontent.com/assets/159209/16606078/c83a49fe-42e9-11e6-9c67-f24da84f1b82.png)](https://github.com/ahmetalpbalkan/go-httpbin/)

You can see how sharp and pixel-fitted (https://dcurt.is/pixel-fitting) travis' icon is.

**Comment by shurcooL** [comment]
The `?status.svg` returns an SVG which is vector graphics that renders well at all resolutions. I think that's the solution to this problem.

I'm not sure if there any reasons to even have the .png endpoint.

![](https://godoc.org/github.com/ahmetalpbalkan/go-httpbin?status.svg)

![image](https://cloud.githubusercontent.com/assets/1924134/16607626/1a61ad5e-42f8-11e6-97bd-95f1037e5e72.png)

I've made https://github.com/ahmetalpbalkan/go-httpbin/pull/1.

What do people think of deprecating the .png endpoint? Are there any current evergreen browsers (IE 6 doesn't count) that can't render svg?

**Comment by shurcooL** [comment]
What do people think of deprecating the .png endpoint? Are there any current evergreen browsers (IE 6 doesn't count) that can't render svg?

**Comment by ahmetalpbalkan** [comment]
Ah I was not aware of status.svg
