### ISSUE TITLE
Does not show up in "shlex" search results: github.com/google/shlex

### ISSUE THREAD

**Issue by ahmetalpbalkan** [golang/gddo#423]
https://godoc.org/github.com/google/shlex page exists but does not show up in godoc.org search results: https://godoc.org/?q=shlex

Screenshot:

> ![image](https://cloud.githubusercontent.com/assets/159209/16673168/a4b7c52e-4460-11e6-9142-4679e2733f5c.png)

**Comment by shantuo** [comment]
Some of the packages may be not reindexed due to some reason. Refreshed and it shows now.
