### ISSUE TITLE
size truncation hides some legitimate packages

### ISSUE THREAD

**Issue by rogpeppe** [golang/gddo#425]
It would be great if https://godoc.org/github.com/aws/aws-sdk-go/service/ec2 could
show the package doc and not "The documentation displayed here is incomplete.".

Even just showing the index would be more useful.

**Comment by dolmen** [comment]
This seems fixed, isn't it?

**Comment by shurcooL** [comment]
It looks that way to me, yes. I'm not seeing the "The documentation displayed here is incomplete." text anymore.

The commit that resolved this might've been 95a6c634fc4948a832d26a56e029b7f709cab144.

**Comment by shantuo** [comment]
Yes, for now at least. Though it only bumped the limit to a large number that satisfies 99.9...% of the packages we have. This limit should really go away and we need to re-work some of that fetching process.
