### ISSUE TITLE
Don't expand internal package when listing subdirectories

### ISSUE THREAD

**Issue by rakyll** [golang/gddo#430]
Internal package is not user facing hence should not populate the directory listings such as the case at https://godoc.org/google.golang.org/cloud#pkg-subdirectories. golang.org/x/tools/cmd/godoc entirely hides the internals. We should either hide the internal or should stop expanding them in the listings.

**Comment by broady** [comment]
It's still useful to have them, but I agree that demoting them would be useful.

Maybe they could be at the bottom, or greyed out, or under a dropdown:

`> Internal packages (3)`

**Comment by normanvashon** [comment]
Related issue: https://github.com/golang/gddo/issues/408

**Comment by rakyll** [comment]
Duplicate of https://github.com/golang/gddo/issues/402.
