### ISSUE TITLE
New context package not found

### ISSUE THREAD

**Issue by normanvashon** [golang/gddo#436]
The page https://godoc.org/context is not found.  It looks like other 1.7 pages are found.

**Comment by shurcooL** [comment]
Same reason as in https://github.com/golang/gddo/issues/427#issuecomment-236696010.

`gosrc` package needs to be updated so that `gosrc.IsGoRepoPath("context")` returns true, not false.

**Comment by shurcooL** [comment]
What commit was this resolved in? Or was it resolved in another way?

**Comment by shantuo** [comment]
https://go-review.googlesource.com/c/27111/

I don't know why it didn't close this automatically.

**Comment by shurcooL** [comment]
That CL has been merged into https://go.googlesource.com/gddo (the canonical source), but it's not showing up on this github repo (which is a mirror of the canonical source):

https://github.com/golang/gddo/commits/master

![image](https://cloud.githubusercontent.com/assets/1924134/17828519/c4bff56c-6648-11e6-89d8-9aebac30988a.png)

Is something wrong with the syncing of this mirror?

**Comment by shurcooL** [comment]
I'll try pushing the latest commit from https://go.googlesource.com/gddo to this github mirror, since it's still not showing up here (it should be harmless to try). We'll see if the mirror sync bot undoes it, or something else happens.

**Comment by shurcooL** [comment]
Well, I pushed it manually, and it's still here after a few mins. So the mirror is up to date now.

Based on that, I suspect the bot that used to perform the syncing of this mirror repo isn't doing that anymore.

**Comment by shantuo** [comment]
@adg Hi Andrew, do you have any idea on this?

**Comment by adg** [comment]
cc @bradfitz @quentinmit 

Maybe the commit watcher hung?

I don't see anything wrong in http://farmer.golang.org/debug/watcherlogs or http://farmer.golang.org/debug/watcher/gddo

**Comment by shurcooL** [comment]
I just want to point out that the bot appears to be working now. It has pushed a [recently merged upstream commit](https://go-review.googlesource.com/#/c/27467/) successfully, see https://github.com/golang/gddo/issues/437#event-764832907.

<img width="648" alt="screen shot 2016-08-23 at 7 55 58 pm" src="https://cloud.githubusercontent.com/assets/1924134/17916825/a70217f0-696b-11e6-97db-953b91e55520.png">

**Comment by shantuo** [comment]
Yes, I don't know what was wrong. The last two CL were both submitted by me. Only one of them didn't merge.
