### ISSUE TITLE
Standard cmd packages are not listed

### ISSUE THREAD

**Issue by rakyll** [golang/gddo#437]
Godoc.org is not serving cmd/ packages, see https://godoc.org/cmd.

It is pretty unexpected given the amount of documentation exist on the binary docs and I don't see a reason why we prefer to serve standard libraries but not tools.

**Comment by normanvashon** [comment]
Same issue as https://github.com/golang/gddo/issues/437.  The packages are not picked up by `go list std`.

**Comment by shurcooL** [comment]
I've made a CL that resolves this issue, see https://go-review.googlesource.com/#/c/27467/.

### Screenshots

![screen shot 2016-08-21 at 10 46 54 pm](https://cloud.githubusercontent.com/assets/1924134/17845577/c7ee8d6a-67f7-11e6-95af-4fab29fa2b99.png)
![screen shot 2016-08-21 at 10 46 57 pm](https://cloud.githubusercontent.com/assets/1924134/17845578/c7f0c792-67f7-11e6-8f28-c89cce97c75a.png)
![screen shot 2016-08-21 at 10 47 04 pm](https://cloud.githubusercontent.com/assets/1924134/17845579/c8001f6c-67f7-11e6-820b-99ce05eac6e3.png)
