### ISSUE TITLE
talksapp: do not fail with 500 when memcache set fails

### ISSUE THREAD

**Issue by campoy** [golang/gddo#438]
Currently logs show that we respond with 500 whenever a `set` to memcache fails.
This is not necessary.

Example:

```
20:32:25.414 HEAD 500 63 B 253 ms Twitterbot/1.0 /github.com/tcnksm/talks/2016/08/go1.7/go1.7.slide  199.59.148.209 
20:32:25.428 Fetching presentation github.com/tcnksm/talks/2016/08/go1.7/go1.7.slide.
20:32:25.667 Internal error memcache: item not stored
```

**Comment by shurcooL** [comment]
Do you know what is an example reason why setting to memcache would fail?

**Comment by campoy** [comment]
memcache being down would be an example :-)

**Comment by shurcooL** [comment]
I see. And we want to treat that as a non-critical failure when serving a presentation page. Makes sense, thanks!
