### ISSUE TITLE
Close Method

### ISSUE THREAD

**Issue by xing00lian** [golang/gddo#442]
why this NewClient has no Close method?

**Comment by shurcooL** [comment]
@xing00lian, what NewClient are you referring to? There's not enough information in this issue.

**Comment by xing00lian** [comment]
In go-hbase package,
Method: func NewClient(zkHosts []string, zkRoot string) *Client
this 'client' has no Close method?

**Comment by shurcooL** [comment]
Are you talking about `github.com/pingcap/go-hbase` package? You should direct your question at that package, its developers/maintainers and users.

This issue tracker is for tracking bugs in the gddo project (as well as talksapp and lintapp), so this is not the right place to ask about this.

Please see https://golang.org/wiki/Questions.
