### ISSUE TITLE
usability: Provide redirect when "godoc.org" prepended to Github, Bitbucket url

### ISSUE THREAD

**Issue by kevinburke** [golang/gddo#444]
Frequently I will want to access godoc.org by prepending "godoc.org" to a github.com url. For example, a Google search for "etcd clientv3" leads me to:

https://github.com/coreos/etcd/tree/master/clientv3

To get from here to the godoc, I have to take two steps:

1) Insert "godoc.org/" after the "https://".
2) Remove "/tree/master" from the URL.

It would be nice if godoc.org could remove /tree/&lt;branch or blob ID&gt; from the URL automatically, by redirecting to the correct location. I guess one reason not to do this would be you could theoretically have a valid package in a /tree/master subdirectory, which would fail the redirect.

You could see how many people are trying to do this by grepping the godoc.org logs for "/tree/master" or "/blob/master" or "/tree|blob/\s+". It might be just me :(

**Comment by garyburd** [comment]
Insert "http://godoc.org?q=" in front of the URL.  The [bookmarklet](https://godoc.org/-/about#bookmarklet) automates this action.

**Comment by stephenmw** [comment]
I like this idea, but it is ambiguous. We would need to first check if it is valid, then check if removing tree/.*?/ fixes it.

**Comment by garyburd** [comment]
The existing one step solution is to insert `godoc.org/?q=` at the beginning of the URL. The [bookmarklet](https://godoc.org/-/about#bookmarklet) automates this step.

Example: [godoc.org/?q=https://github.com/coreos/etcd/tree/master/clientv3](https://godoc.org/?q=https://github.com/coreos/etcd/tree/master/clientv3) redirects to https://godoc.org/github.com/coreos/etcd/clientv3

**Comment by kevinburke** [comment]
Fine with me
