### ISSUE TITLE
database: bad syntax for struct tag value

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#453]
Originally reported by @shawnps in [#452](https://github.com/golang/gddo/pull/452/files), there's a missing closing double quote in the struct tag.

`vet` catches this:

```
database $ go tool vet .
database.go:70: struct field tag `json:"import_count` not compatible with reflect.StructTag.Get: bad syntax for struct tag value
```

**Comment by stephenmw** [comment]
Out for review: https://go-review.googlesource.com/c/32829/
