### ISSUE TITLE
CI is failing.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#454]
Travis CI build status is currently failing.

![image](https://cloud.githubusercontent.com/assets/1924134/20041893/fbfbdcca-a424-11e6-8a2d-f6b326d904f7.png)

It been failing on master for the last 26 days:

https://travis-ci.org/golang/gddo/builds

The last successful build was https://travis-ci.org/golang/gddo/builds/166968203. The first failing commit was bd3dc62b21ddf0db110800ab97a37e70933bee5a.

**Comment by stephenmw** [comment]
I didn't even know we had a travis. Apparently my vendoring did this but the bug is with travis, not the code.

**Comment by stephenmw** [comment]
Hm, looks like the vendoring is messing with the talks app. I will look into this later.

**Comment by stephenmw** [comment]
Fixed by https://go-review.googlesource.com/c/33200/
