### ISSUE TITLE
godoc.org is blocked to Iranian users

### ISSUE THREAD

**Issue by mASOUDd** [golang/gddo#457]
![google](https://cloud.githubusercontent.com/assets/828670/20270586/defb0a32-aa9c-11e6-8cf5-dd9a102b5663.png)
This website is not accessible for Iranian users. Unless this is intended, it is a bug.

**Comment by shantuo** [comment]
godoc.org is hosted on GAE Flex. It may be Google Cloud that blocks access from Iran.

**Comment by mASOUDd** [comment]
I just checked again and now it is accessible.
