### ISSUE TITLE
examples: Package example not expanded when given link with example fragment

### ISSUE THREAD

**Issue by mewmew** [golang/gddo#459]
In general, examples are expanded when given the full link to the example as specified by the relevant fragment identifier (e.g. `#example-ACLHandle-Delete`).

For example, visiting the link https://godoc.org/cloud.google.com/go/storage#example-ACLHandle-Delete expands the code example and displays the following code.

```go
ctx := context.Background()
client, err := storage.NewClient(ctx)
if err != nil {
    // TODO: handle error.
}
// No longer grant access to the bucket to everyone on the Internet.
if err := client.Bucket("my-bucket").ACL().Delete(ctx, storage.AllUsers); err != nil {
    // TODO: handle error.
}
```

However, the same method cannot be used to expand package level examples using fragment identifiers (i.e. `#ex-package`).

For example, visiting the link https://godoc.org/github.com/llir/llvm/ir#ex-package does *not* expand the code example, but a user would have to click to reveal the follow code.

```go
// This example produces LLVM IR code equivalent to the following C code,
// which implements a pseudo-random number generator.
//
//    int abs(int x);
//
//    int seed = 0;
//
//    // ref: https://en.wikipedia.org/wiki/Linear_congruential_generator
//    //    a = 0x15A4E35
//    //    c = 1
//    int rand(void) {
//       seed = seed*0x15A4E35 + 1;
//       return abs(seed);
//    }

// Create convenience types and constants.
i32 := types.I32
zero := constant.NewInt(0, i32)
a := constant.NewInt(0x15A4E35, i32) // multiplier of the PRNG.
c := constant.NewInt(1, i32)         // increment of the PRNG.

// Create a new LLVM IR module.
m := ir.NewModule()

// Create an external function declaration and append it to the module.
//
//    int abs(int x);
abs := m.NewFunction("abs", i32, ir.NewParam("x", i32))

// Create a global variable definition and append it to the module.
//
//    int seed = 0;
seed := m.NewGlobalDef("seed", zero)

// Create a function definition and append it to the module.
//
//    int rand(void) { ... }
rand := m.NewFunction("rand", i32)

// Create an unnamed entry basic block and append it to the `rand` function.
entry := rand.NewBlock("")

// Create instructions and append them to the entry basic block.
tmp1 := entry.NewLoad(seed)
tmp2 := entry.NewMul(tmp1, a)
tmp3 := entry.NewAdd(tmp2, c)
entry.NewStore(tmp3, seed)
tmp4 := entry.NewCall(abs, tmp3)
entry.NewRet(tmp4)

// Print the LLVM IR assembly of the module.
fmt.Println(m)
```

Is this intended behaviour?

Note that the package level example is identified by the stylesheet (but not the JavaScript?) as the background colour of the example is highlighted in yellow.

**Comment by shurcooL** [comment]
I think this is a duplicate of #443, isn't it?

**Comment by mewmew** [comment]
Oh, you are right indeed.

Visiting https://godoc.org/github.com/llir/llvm/ir#example-package correctly expands the code example.

Interestingly, the background is not coloured yellow when using the [#example-package](https://godoc.org/github.com/llir/llvm/ir#example-package) but is when using the [#ex-package](https://godoc.org/github.com/llir/llvm/ir#ex-package) fragment identifier. Is this intended? Why do there exist two link formats?

I'll close this issue for now as it is indeed a duplicate.

Thank you!
