### ISSUE TITLE
Google Chrome on OSX - Always Shows Mobile Version

### ISSUE THREAD

**Issue by Kent-H** [golang/gddo#460]
On Chrome for OS X (El Capian, version 10.11.6), godock.org always shows me the mobile-friendly version of the site, compressing everything into a thin column down the middle of the page.  This makes the docs very difficult to read.

Screenshot:

<img width="1291" alt="screen shot 2016-12-05 at 10 14 47 am" src="https://cloud.githubusercontent.com/assets/8741399/20892329/c3e61d46-badb-11e6-87c6-356af269e0c1.png">

**Comment by shurcooL** [comment]
1. What version of Chrome are you using?
2. Have you tried emptying cache and doing a hard reload?
3. What about opening the same URL inside an incognito window?

I can't reproduce in latest stable Chrome (55.0.2883.75) and latest stable macOS (10.12.1).

https://godoc.org/golang.org/x/net/html

![image](https://cloud.githubusercontent.com/assets/1924134/20899468/865395fe-baf8-11e6-8bc5-66eb4eccfe97.png)

**Comment by Kent-H** [comment]
Clearing browsing history/clearing cookies/clearing cache didn't fix the issue, and it persisted in incognito mode.  

However, when I signed out of chrome itself, the problem disappeared.

It seems to be all OK now.
