### ISSUE TITLE
Can not view gddo page for a large package

### ISSUE THREAD

**Issue by wgj** [golang/gddo#467]
When viewing the gddo page for [github.com/softlayer/softlayer-go](https://godoc.org/github.com/softlayer/softlayer-go/services), I see a message saying "The documentation displayed here is incomplete. Use the godoc command to read the complete documentation." instead of the expected gddo representation of the package's GoDoc comments.

[Screenshot](https://cloud.githubusercontent.com/assets/463564/21663360/8a954712-d294-11e6-8345-28d989e1d93a.png)

Chrome Version 55.0.2883.95 (64-bit)
MacOS 10.12.2

This appears to be a recurrence of the package size issue in #175.

**Comment by shantuo** [comment]
The limit size now is 400000, I can try re-examine all the truncated packages and see by how much we want to bump up it.

**Comment by shurcooL** [comment]
Resolved by 95a6c63, closing.
