### ISSUE TITLE
exported methods not visible on unexported struct

### ISSUE THREAD

**Issue by splace** [golang/gddo#472]
see; https://godoc.org/github.com/splace/os/xattribs

surely when you don’t export a struct, to force it to be only made in a controlled way, through a constructor, you still do want to see documentation on its exported methods?

**Comment by shurcooL** [comment]
This is how `godoc` (the command) operates, gddo mimics that behavior.

Have you considered either returning an exported type, or an interface that the unexported type implements?

**Comment by splace** [comment]
probably should do that now, the constructor has become trivial due to other changes. Just didn't seem like that odd a pattern.
has come up a few times; https://github.com/golang/go/issues/2273
