### ISSUE TITLE
Server dies when searching packages.

### ISSUE THREAD

**Issue by Bren2010** [golang/gddo#474]
This issue occurs when running gddo-server on localhost. If the user tries to search, the server dies after failing to make a GCE API request. I don't see any obvious way to work around this issue.

```
$ gddo-server -db-server=redis://localhost:9351
2017/02/22 17:02:40 Starting server, os.Args=gddo-server -db-server=redis://localhost:9351
2017/02/22 17:02:59 Metadata fetch failed: Get http://metadata/computeMetadata/v1/instance/attributes/gae_project: dial tcp: lookup metadata: no such host
$ echo $?
1
```

**Comment by shantuo** [comment]
Yeah it relies on App Engine now and if you want to run gddo-server on localhost you need to run the dev_appserver. See instructions here: https://github.com/golang/gddo/wiki/Development-Environment-Setup
