### ISSUE TITLE
Doc showing data from old commit after refresh.

### ISSUE THREAD

**Issue by daved** [golang/gddo#483]
Affected repo: https://godoc.org/github.com/jmoiron/sqlx

Earlier this morning the doc appeared to be correct.  A merge was performed adding a new method a short while ago (jmoiron/sqlx@3564e3a). After refreshing the godoc and a hard reload in the browser, the doc shows outdated info.

I'm unsure of which commit this data represents, but it is old enough to be missing not just the method added today, but also more recent functions and methods which receive context.Context.

**Comment by shurcooL** [comment]
I can confirm, this looks like a problem.

I'm not sure if it's a bug in the code, or an operations issue (or both).

**Comment by shurcooL** [comment]
One hunch to look into. The func that was added recently is inside a .go file with `// +build go1.8`.

We should confirm that godoc.org is using a Go 1.8+ build context.

**Comment by shantuo** [comment]
@stephenmw Could you take a look? This works fine with my own deployment.

**Comment by shurcooL** [comment]
I've confirmed my hunch was right.

I created a package for debugging this issue at https://github.com/shurcooL/play/commit/11633f2cd8c683fe0a40444edad2896038055f5a.

godoc.org displays "1.7":

https://godoc.org/github.com/shurcooL/play/219

![image](https://cloud.githubusercontent.com/assets/1924134/24976451/7f78f59a-1f97-11e7-8d5c-1a379874e3b5.png)

That confirms it's using the Go 1.7 build context, but it should be updated to use Go 1.8.

**Comment by shantuo** [comment]
Thanks @shurcooL , yeah it seems to be an operations issue. I just did a new deployment and it seems work fine now.
