### ISSUE TITLE
Incorrect directory list

### ISSUE THREAD

**Issue by buchanae** [golang/gddo#486]
https://godoc.org/github.com/ohsu-comp-bio/funnel

Yesterday we moved lots of code around in Funnel. The gddo directory list shows directories from before the move. Everything under "src/funnel/*" was moved to the repo root. I've hit the "refresh" link many times and waited overnight, hoping time would fix this.

Should I keep waiting, or does this need some manual intervention? Is everything working properly and I'm missing something on our side?

**Comment by shurcooL** [comment]
It would've been helpful if you posted a screenshot of what you're seeing, so I could compare it to what I'm seeing. But I think I know what's going on.

The current behavior of godoc.org is that it refreshes only the package you're viewing, it doesn't do anything recursively.

So if you've added or removed packages, you need to visit their own pages for godoc.org to pick up the changes.

If you visit the "src/funnel/*" packages, you'll get "Not Found" and they'll be updated as packages that no longer exist, and not show up in the directory list.

For example, before:

![image](https://cloud.githubusercontent.com/assets/1924134/25495113/13c3c564-2b4a-11e7-9553-02161db757df.png)

When I click on `src/funnel/cmd/task` link:

![image](https://cloud.githubusercontent.com/assets/1924134/25495133/258f2d6a-2b4a-11e7-893e-3ac69e3637fd.png)

After (notice `src/funnel/cmd/task` entry is gone):

![image](https://cloud.githubusercontent.com/assets/1924134/25495141/2c7276c8-2b4a-11e7-82b6-a633eeb0713d.png)

Does that help explain what's going on?

**Comment by buchanae** [comment]
It seems to be resolved now. Thanks for the quick response and helpful answer. You're right, screenshots are gold, sorry for making you understand my early-morning braindump :)

I wouldn't say the experience is intuitive or expected though. If I hit "refresh" I expect that page to come back correct. Maybe that's another issue, and maybe it's not common enough to worry about.

**Comment by shurcooL** [comment]
Yes, the behavior is definitely not the most user friendly. With work and computing resources available (because it'd be more expensive to refresh directories recursively), it can be improved. But it be a new feature, not a bug.

**Comment by shantuo** [comment]
Yes I agree. godoc.org does not do "directory updates" because of the GitHub rate limit. We try not to update/refresh too often to avoid hitting the limit. With the fast growing speed of the total package number and most of which comes from GitHub, this becomes more significant than before and needs some bit of rethinking.

**Comment by buchanae** [comment]
Maybe there's a simple improvement in being able to prune the "src" subtree when refreshing the root? If the root doesn't contain "src", then you can remove any directory in the list with that prefix right? If I understand correctly, that's would be possible without adding any additional GitHub queries.
