### ISSUE TITLE
problem with google.golang.org/api/compute/v1 

### ISSUE THREAD

**Issue by jare19** [golang/gddo#488]
Apologies if this is not the correct method to reports something like this, but at godoc.org/google.golang.org/api/compute/v1 I see:
`The documentation displayed here is incomplete. Use the godoc command to read the complete documentation.`
As of now, the page is not very useful.
Thanks

**Comment by shurcooL** [comment]
This must be because that package documentation has grown larger than the max size currently allowed by gddo.

See #175 and #467 for related issues. /cc @shantuo

**Comment by jare19** [comment]
Hopefully it is fixed soon, but judging by the lack of attention from the referenced issues... I have my doubts.
