### ISSUE TITLE
gosrc: isQuickFork appears to be broken.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#492]
See comment I left on the CL that last touched the `isQuickFork` function:

https://go-review.googlesource.com/c/24793/9/gosrc/github.go#194

As far as I can tell, `isQuickFork` will always return false, even if the fork is a quick fork, if the original repository has at least 3 commits. Most real repositories have at least 3 commits.

It looks like `isQuickFork` used to rely on the presence of a commit date filter when fetching commits from GitHub API:

```Go
url += fmt.Sprintf("?since=%s", repo.CreatedAt.Format(time.RFC3339))
```

But that same CL removed that filter (likely for other needs), without making appropriate changes to `isQuickFork`.

**Comment by shantuo** [comment]
I think you may be right, I am looking at it and trying to find out why I deleted that line of code. I guess it might have introduced some other issue. If that's the case maybe we should think of another way to do that.

**Comment by shurcooL** [comment]
The smallest change that would fix `isQuickFork` that I can see is to have it ignore/skip over all commits that are before the fork creation date, in the for loop that increments `n`.

**Comment by shurcooL** [comment]
[CL 47352](https://golang.org/cl/47352) mentions this issue.
