### ISSUE TITLE
http://godoc.org should redirect to https://godoc.org.

### ISSUE THREAD

**Issue by shurcooL** [golang/gddo#493]
This is a feature request. Given it's 2017, unless there's a specific reason for it, I believe http protocol should be used only to redirect all queries to https.

I'm pretty sure this used to be the case in the past, but it feels like something changed/happened in the last few weeks and http://godoc.org/ no longer redirects to https://godoc.org/.

Browsers show increasingly scary status for http:// addresses, which is distracting from the documentation I want to read. I visit a lot of godoc.org pages via autocomplete, and for some reason, they default to http://, so I have to manually edit the URL to https://.

Is there a specific reason not to redirect all http:// to https://? If not, I think this should be done.

**Comment by stephenmw** [comment]
Thanks for the report. We moved from App Engine Managed VMs to App Engine Flex. That disabled our redirect. It looks like I will need to add the redirect to the godoc code itself.

**Comment by shurcooL** [comment]
Something like this, perhaps:

```Go
// httpToHTTPSRedirector redirects all requests from http to https.
type httpToHTTPSRedirector struct{}

func (httpToHTTPSRedirector) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	w.Header().Set("Connection", "close")
	u := *req.URL
	u.Scheme = "https"
	u.Host = req.Host
	http.Redirect(w, req, u.String(), http.StatusMovedPermanently)
}
```

**Comment by kevinburke** [comment]
https://go-review.googlesource.com/c/49650/

**Comment by shurcooL** [comment]
The change still needs to be deployed and tested.

**Comment by shurcooL** [comment]
@stephenmw Has the new version been deployed yet? The http -> https redirection is not yet taking place.

**Comment by shantuo** [comment]
Deploying now.

**Comment by shurcooL** [comment]
I can see it's working now! \o/ Shall we close this issue?

**Comment by shantuo** [comment]
Yes it's working, thanks!
