### ISSUE TITLE
godoc.org is not listing the directories in bluemix-go project repo

### ISSUE THREAD

**Issue by ashishth09** [golang/gddo#494]
https://github.com/ibm-bluemix/bluemix-go has packages like `mccpv2` etc 

https://github.com/IBM-Bluemix/bluemix-go/blob/master/api/mccp/mccpv2/api_service.go

But the godoc at https://godoc.org/github.com/IBM-Bluemix/bluemix-go doesn't show them

**Comment by shurcooL** [comment]
godoc.org doesn't immediately recursively look for all packages inside a repository. If it's not listed, you have to visit its URL directly manually, and it'll display the documentation and update index.

Try visiting https://godoc.org/github.com/IBM-Bluemix/bluemix-go/api/mccp/mccpv2.

**Comment by ashishth09** [comment]
Thanks @shurcooL. I can live with that. Is it something which will be worked in future , though?

**Comment by shurcooL** [comment]
In a similar past issue, I [wrote](https://github.com/golang/gddo/issues/486#issuecomment-297790837):

> Yes, the behavior is definitely not the most user friendly. You're not the first who ran into this.
>
> With work and computing resources available (because it'd be more expensive to refresh directories recursively), it can be improved. But it be a new feature, not a bug.

I'm not aware of an issue tracking the feature request, nor anyone actively working on it.

#367 is somewhat related, but I'm not sure what its state is. It'd be better to open a new one if you want to explicitly request this feature.

**Comment by ashishth09** [comment]
Opened #495
