### ISSUE TITLE
probable mat64 documentation error.

### ISSUE THREAD

**Issue by ngc5194** [golang/gddo#497]
In the documentation for github.com/gonum/matrix/mat64 for the "Eigen" section and "func (*Eigen) Factorize subsection, just under the second boxed code/math there is the statement: "... and (lambda) is the corresponding eigenvector."  I'm reasonably sure this should be "eigenvalue", not "eigenvector".

**Comment by shurcooL** [comment]
Thanks for reporting, but this is the wrong issue tracker. You should make this report in the [issue tracker for the github.com/gonum/matrix repository](https://github.com/gonum/matrix/issues) instead, since that's the project where the issue is. This issue tracker is for the gddo project.

**Comment by ngc5194** [comment]
On Sun, Jul 16, 2017 at 06:01:37AM +0000, Dmitri Shuralyov wrote:
> Thanks for reporting, but this is the wrong issue tracker. You should make this report in the [issue tracker for the github.com/gonum/matrix repository](https://github.com/gonum/matrix/issues) instead, since that's the project where the issue is. This issue tracker is for the gddo project.

It's where the link on the page took me.  Whatever, I'm just trying to
help.  If you guys can't keep this stuff straight, that's your thing,
I guess.

-- 
Nick Christenson
npc@gangofone.com
