### ISSUE TITLE
Should Godoc.org error when query params are added?

### ISSUE THREAD

**Issue by joncalhoun** [golang/gddo#500]
I was writing an email with a link to the `cmp` package (http://godoc.org/github.com/google/go-cmp/cmp) using Drip.co and when I sent myself a test email they added on a random URL query param - http://godoc.org/github.com/google/go-cmp/cmp?__s=XXXXXXXX

When I visit the first link everything works, but the second errors. Is this intentional?

**Comment by shurcooL** [comment]
That feels like a bug to me. I think unknown/unsupported queries should either be ignored, or the error message should mention "unrecognized query parameters". It currently says "Not Found" as if the repository is not found, that's not accurate.

As a data point, github.com ignores unknown queries. E.g., https://github.com/golang/gddo/issues/500?__s=XXXXXXXX takes you here and works fine.

**Comment by shurcooL** [comment]
Reopening for deploy and to verify the fix works as expected.

**Comment by shantuo** [comment]
Thanks for the change @m90 ! Just deployed a new version and switched it to default.
