### ISSUE TITLE
talks: error serving slides with https

### ISSUE THREAD

**Issue by sbinet** [golang/gddo#501]
hi,

it seems the `talks.godoc.org` app is down or something:

```sh
$> curl https://talks.godoc.org/github.com/sbinet/jdev-go-2017/talk.slide
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to talks.godoc.org:443 
```

it's properly serving `http` though.

**Comment by shurcooL** [comment]
/cc @stephenmw @shantuo

Not sure who maintains the operations side of `talksapp`, hopefully it's one of you.

**Comment by stephenmw** [comment]
Pushed fix, let me know if it still isn't working in 30 minutes. This was completely my fault.

**Comment by sbinet** [comment]
thanks :)
