### ISSUE TITLE
Seems like godoc.org is down

### ISSUE THREAD

**Issue by Lord-Protector** [golang/gddo#502]
Any news?

**Comment by ranaharoni** [comment]
1+

**Comment by klingtnet** [comment]
Can be closed, [godoc.org](https://godoc.org/) is up again.

**Comment by shurcooL** [comment]
I'm seeing a timeout too.

/cc @shantuo @stephenmw

**Comment by klingtnet** [comment]
Seems to be up again.

**Comment by shurcooL** [comment]
I don't know who fixed it, but the issue is resolved.

**Comment by shantuo** [comment]
Just deployed a temp fix, still working on a permanent solution.

**Comment by shurcooL** [comment]
I see. Let me know if I can be of assistance.

(Also, feel free to re-open this issue if you want to use it to track that task. Or file a new one referencing this.)

**Comment by Samuyi** [comment]
can't access godoc.org, seems like server is down.

**Comment by klingtnet** [comment]
Seems to be up again.

**Comment by pariola** [comment]
can't access godoc.org, seems like server is down.

**Comment by dmitshur** [comment]
@pariola I'm not seeing any issues; it's up at this time.

**Comment by timolinn** [comment]
I can't access godoc.org and pkg.go.dev

**Comment by timolinn** [comment]
Resolved, router issues :)
