### ISSUE TITLE
builtin package is missing

### ISSUE THREAD

**Issue by monicaq** [golang/gddo#503]
The page https://godoc.org/builtin is not found. This page is linked from most other pages on your website.

**Comment by shantuo** [comment]
Redeploying with 1.9 should solve the problem.

**Comment by shantuo** [comment]
Cannot deploy now due to issue #504

**Comment by shurcooL** [comment]
> Redeploying with 1.9 should solve the problem.

Just wondering, but why is that the case? `builtin` is not a new package to Go 1.9, it was there before.

**Comment by shantuo** [comment]
It uses type alias, current gddo binary cannot resolve that when it tries to update the package.

**Comment by shurcooL** [comment]
This seems to fixed indirectly by the [same change](https://github.com/golang/go/issues/21601#issuecomment-325032502) that was used to fix https://golang.org/pkg/builtin/.

Shall we close this @shantuo, or is there more to be done here?

**Comment by shantuo** [comment]
No, it works now.
