### ISSUE TITLE
dev documentation is out of date

### ISSUE THREAD

**Issue by andybons** [golang/gddo#515]
From following https://github.com/golang/gddo/wiki/Development-Environment-Setup, I’m unable to get a working local dev, with dev_appserver.py $GOPATH/src/github.com/golang/gddo/gddo-server spinning up a server, but returning a 503 when visiting http://localhost:8080/github.com/golang/gddo/gddo-server

**Comment by Carpetsmoker** [comment]
The current instructions worked well for me just now.

**Comment by jackwilsdon** [comment]
It looks like the docs were updated: https://github.com/golang/gddo/wiki/Development-Environment-Setup/_compare/f6597a85caca58ac7198a0f0cded30248b98586b...30f57cc880a2f18e198488f36fad673e4377e8d8

**Comment by andybons** [comment]
So they were. Thanks for pointing that out.
