### ISSUE TITLE
Adult-oriented repositories under Popular Packages

### ISSUE THREAD

**Issue by schmichael** [golang/gddo#524]
The "Popular Packages" listing on gddo's landing page includes a client library for a pornography site (`github.com/pdevty/xvideos`):

![image 2](https://user-images.githubusercontent.com/113362/32399176-3bc5cd1c-c0b1-11e7-864e-081b9c3679ac.png)

Perhaps I've heard Ira Glass utter "warning to parents but this story acknowledges the existence of sex" one too many times, but perhaps adult-oriented content should be kept off the home page as this is presumably meant to be a site for use by anyone of any age.

However, neither the package name nor documentation mentions any explicit content, so perhaps there's nothing to worry about.

**Comment by shurcooL** [comment]
Not related to the package content, but I’m very puzzled how the package is showing up in the list of popular packages while having zero importers (at this time):

https://godoc.org/github.com/pdevty/xvideos?importers

I thought that list displayed most imported packages.

**Comment by dlsniper** [comment]
Not related either but does anyone think that sarama is really that popular? And it's been there since I know that website (for like 4 years now).

**Comment by schmichael** [comment]
I would be thrilled if the solution to this issue was that there's a bug in the Popular Packages code as I would be surprised if adult-oriented packages were actually ever in the most popular list by any reasonable metric.

**Comment by schmichael** [comment]
This has been fixed.
