### ISSUE TITLE
Missing Interfaces

### ISSUE THREAD

**Issue by aletheia7** [golang/gddo#530]
https://godoc.org/github.com/mattn/go-sqlite3 is missing interface definitions:
```
type Module interface
type VTab interface
...
```
in https://github.com/mattn/go-sqlite3/blob/master/sqlite3_vtable.go

Perhaps this is caused by the +build line? https://github.com/mattn/go-sqlite3/blob/d5ffb5c0cca8778699a929b236766f4a7af674e8/sqlite3_vtable.go#L5

**Comment by shurcooL** [comment]
> Perhaps this is caused by the +build line? https://github.com/mattn/go-sqlite3/blob/d5ffb5c0cca8778699a929b236766f4a7af674e8/sqlite3_vtable.go#L5

That seems to be the explanation. godoc.org doesn't have support for viewing documentation with custom build tags applied.
