### ISSUE TITLE
talks.godoc.org still links to go-talks.appspot.com

### ISSUE THREAD

**Issue by mvdan** [golang/gddo#532]
> The syntax for URLs is:
> http://go-talks.appspot.com/github.com/owner/project/file.ext
> http://go-talks.appspot.com/github.com/owner/project/sub/directory/file.ext

I realise that both work, but talks.godoc.org is more likely to survive in the long term and it's a better URL to suggest to users.

**Comment by mvdan** [comment]
Alternatively, I'm sure there would be a way to make the template use whatever domain it's being served on.

**Comment by leighmcculloch** [comment]
Gerrit doesn't seem to cross post, but I opened a fix for this here:
https://go-review.googlesource.com/#/c/gddo/+/95256

While I think that it might be nice to display whatever the hostname is, it's simpler and less logic to simply update the domain with the canonical location.

**Comment by shurcooL** [comment]
Reopening for tracking when the fix has been deployed.

**Comment by shantuo** [comment]
Deployed now.
