### ISSUE TITLE
"internal" directories no longer show subdirectory listing

### ISSUE THREAD

**Issue by dmitshur** [golang/gddo#533]
This used to work not long ago, and I suspect (but haven't verified) that this is related to the recent change in #402. /cc @rakyll

Normally, directories that have no .go files (i.e., no Go package) but contain subdirectories with Go packages are displayed on godoc.org as a simple directory listing. E.g.:

-	https://godoc.org/compress
-	https://godoc.org/go

![image](https://user-images.githubusercontent.com/1924134/36044368-62cec904-0da0-11e8-8ff9-8e57c3428861.png)

However, now, if the directory is named "internal", then it always appears without any subdirectories, e.g.:

-	https://godoc.org/go/internal
-	https://godoc.org/cmd/go/internal

![image](https://user-images.githubusercontent.com/1924134/36044410-93c76ae8-0da0-11e8-98cf-9cdf0da4f8e3.png)

This bug hurts usability because it's no longer possible to reliably traverse, explore, discover, find packages on godoc.org. Also, it makes certain existing links useless. E.g., start at https://godoc.org/go/internal/gcimporter, and click on "internal" link on top:

![image](https://user-images.githubusercontent.com/1924134/36044488-db25305a-0da0-11e8-9b21-3ff4607214ab.png)

You'll get to an empty page.

I used examples from standard library, but this affects all Go packages, including 3rd party ones.

**Comment by rakyll** [comment]
:( Do we want to revert the previous change? I may find sometime later today to fix if it is not critical.

**Comment by shurcooL** [comment]
If no one has time to get to this soon, I think it's better to revert to bring things back to a functional (albeit more noisy) state. Then, the original CL can be iterated on and re-applied without this bug and extra test cases for it.

**Comment by rakyll** [comment]
I sent a CL: https://go-review.googlesource.com/c/gddo/+/93196.

**Comment by shantuo** [comment]
I reverted it to an earlier version.

**Comment by dmitshur** [comment]
> If no one has time to get to this soon, I think it's better to revert to bring things back to a functional (albeit more noisy) state. Then, the original CL can be iterated on and re-applied without this bug and with extra test cases for it.

I sent a revert [CL 130937](https://golang.org/cl/130937). When merged, we can re-open #402 for further tracking of that issue.
