### ISSUE TITLE
github.com/dvyukov/go-fuzz history was rewritten

### ISSUE THREAD

**Issue by AlekSi** [golang/gddo#535]
https://github.com/dvyukov/go-fuzz#history-rewrite
https://godoc.org/github.com/dvyukov/go-fuzz shows old packages, and can't be refreshed. Looks like a manual intervention is required.

**Comment by shantuo** [comment]
There's probably a delay when this package got updated in the queue. It should get updated automatically when gddo tries to update it the packages.

**Comment by AlekSi** [comment]
There is a "Refresh now" link at the bottom that did not work. But now everything is fine.

**Comment by shantuo** [comment]
Yeah, the way it works is not ideal definitely, it only refresh the package itself, not everything under it.
