### ISSUE TITLE
golang.org\x\crypto\ssh\terminal

### ISSUE THREAD

**Issue by Ollicicilly** [golang/gddo#537]
# golang.org/x/crypto/ssh/terminal
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:44: undefined: windows.ENABLE_ECHO_INPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:44: undefined: windows.ENABLE_PROCESSED_INPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:44: undefined: windows.ENABLE_LINE_INPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:44: undefined: windows.ENABLE_PROCESSED_OUTPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:45: undefined: windows.SetConsoleMode
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:64: undefined: windows.SetConsoleMode
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:69: undefined: windows.ConsoleScreenBufferInfo
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:70: undefined: windows.GetConsoleScreenBufferInfo
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:86: undefined: windows.ENABLE_ECHO_INPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:87: undefined: windows.ENABLE_PROCESSED_INPUT
..\src\golang.org\x\crypto\ssh\terminal\util_windows.go:87: too many errors

**Comment by shurcooL** [comment]
Is this a bug report for godoc.org? What is the problem?

**Comment by Ollicicilly** [comment]
This error was received the first time when attempting to install a 3rd party application using go get. In seeing where the problem exists I attempted to install it directly with the same error report being returned. I checked the file in question and it confirmed that the constants are not recognized

**Comment by shurcooL** [comment]
I see. This issue tracker is for tracking bugs related to the `github.com/golang/gddo` project, but your problem is with installing the `golang.org/x/crypto/ssh/terminal` package via `go get`. I'll close it, because this isn't the right place for it.

Please see https://golang.org/wiki/Questions for a better place to ask about your situation.
