### ISSUE TITLE
mgo: 404 error in relevant documentation for Database.Run

### ISSUE THREAD

**Issue by kangxiaoning** [golang/gddo#540]
There is a link in [mgo](https://godoc.org/gopkg.in/mgo.v2#Database.Run) as below:
http://www.mongodb.org/display/DOCS/List+of+Database+CommandSkips
The return code is 404.

**Comment by shantuo** [comment]
This is a bug in mongodb's code comment, which gets parsed in gddo, please file a bug in mongodb's repo.
