### ISSUE TITLE
Talks doesn't support .background

### ISSUE THREAD

**Issue by nezorflame** [golang/gddo#541]
Host any `present` slide with `.background` image.
It won't be shown for your presentation.
Other images seem to work fine.

Is this a bug or `feature`?

**Comment by shurcooL** [comment]
Is this an issue with the [`present`](https://godoc.org/golang.org/x/tools/cmd/present) command? Or just [talks.godoc.org](https://talks.godoc.org)?

**Comment by nezorflame** [comment]
Just talks.godoc.org

**Comment by nezorflame** [comment]
Background works fine when `present` is launched locally.

**Comment by mmcloughlin** [comment]
I'm seeing this too. There seems to be some re-processing of presentations happening which is not re-mapping `.background` URLs to point at github instead. See

https://github.com/golang/gddo/blob/9d8ff1c67be5c2da6321c656913e1fe355991138/gosrc/present.go#L37-L39

Looks like this would not be too hard to fix.

**Comment by mmcloughlin** [comment]
See https://go-review.googlesource.com/c/gddo/+/133235

**Comment by dmitshur** [comment]
@nezorflame (or anyone else), do you know of a sample talk that has a slide with `.background` that can be used to reproduce the bug?

**Comment by nezorflame** [comment]
@dmitshur sure, take mine: https://talks.godoc.org/github.com/nezorflame/golang-talks/2018/05/execution-tracing-in-go1.11/main.slide#1

Source for it: https://github.com/nezorflame/golang-talks/tree/master/2018/05/execution-tracing-in-go1.11

**Comment by mmcloughlin** [comment]
Any thoughts on the CL https://go-review.googlesource.com/c/gddo/+/133235 ?

**Comment by Deleplace** [comment]
@mmcloughlin I read it and tested it locally, everything works fine on my workstation.

**Comment by dmitshur** [comment]
The new version is deployed now, so `.background` should be working. Thank you for the contribution!

**Comment by Deleplace** [comment]
Thank you @dmitshur . It now works fine on the public URL of my slideshow.

**Comment by mmcloughlin** [comment]
We can also test this with the [sample presentation](https://github.com/golang/gddo/tree/cd5c8e2019a6818cd3b0dfd63e27018a2ac2b8cd/gosrc/testdata) that was also included in the CL. This was intended to exercise all possible features of the `present` tool.

https://talks.godoc.org/github.com/golang/gddo/gosrc/testdata/sample.slide

We do indeed see the `.background` correctly, however it seems the the vector graphic is broken.

**Comment by mmcloughlin** [comment]
I'm getting a 403 from https://rawgit.com/golang/gddo/master/gosrc/testdata/gopher.svg

https://rawgit.com says "RawGit has reached the end of its useful life".
