### ISSUE TITLE
talks: support for mathematic equations

### ISSUE THREAD

**Issue by sbinet** [golang/gddo#546]
it would be great to have some support for mathematic equations in talks and `present`.

an obvious candidate would be MathJAx:
- https://www.mathjax.org/#gettingstarted

**Comment by shurcooL** [comment]
If this is a feature request/proposal to `present`, this isn't the right issue tracker. It should be filed in the main Go issue tracker (as stated [here](https://github.com/golang/go/blob/9d84e0edd042bc6ca2a9cf3e402b81d5f27103d5/CONTRIBUTING.md#filing-issues)). E.g., see https://goissues.org/golang.org/x/tools/present or https://goissues.org/golang.org/x/tools/cmd/present.

The scope of https://talks.godoc.org/ (as I understand) is to support/mirror upstream `present` functionality and not deviate from it.

That said, I notice that https://talks.godoc.org/ actually points to *this* issue tracker:

> Report bugs and request features using the GitHub Issue Tracker.

I think we need to fix that to avoid confusion.

**Comment by sbinet** [comment]
ok. closed in favor of https://github.com/golang/go/issues/24574
