### ISSUE TITLE
Remove link to stale go-search.org engine from results page

### ISSUE THREAD

**Issue by dgryski** [golang/gddo#550]
The main page says " last updated 419 days ago."

@daviddengcn: Is this number accurate?  Is the crawler coming back?

**Comment by daviddengcn** [comment]
Yes, it is correct. The current code does not compile (because of dependent package change). It may need some effort to fix it. I cannot guarantee a time of fixing it. Sorry for the inconvenience.

**Comment by daviddengcn** [comment]
I'll make a try this weekend, and post the result here.

**Comment by daviddengcn** [comment]
Update: the code on my local machine is good. Will try push to server tommorrow.

**Comment by daviddengcn** [comment]
The crawling is recovered

**Comment by dgryski** [comment]
Excellent! I'll close this then.

**Comment by daviddengcn** [comment]
Thanks!
