### ISSUE TITLE
not call Flush can also print log realtime

### ISSUE THREAD

**Issue by Liane001** [golang/gddo#552]
like in C++,  we can use logbuflevel=-1 to print log realtime, but in Go, may one flag can do this?

**Comment by shurcooL** [comment]
Hi there,

This is an issue tracker for the gddo project, used to track bugs in it. People who may know the answer to your question are unlikely to see it here.

For asking questions about Go, see one of the forums at https://golang.org/wiki/Questions.

Good luck!
