### ISSUE TITLE
net/http.Cookie is being rendered incorrectly

### ISSUE THREAD

**Issue by bontibon** [golang/gddo#559]
![image](https://user-images.githubusercontent.com/110883/41615675-4651286a-73d2-11e8-8608-a8b238041852.png)

**Comment by shurcooL** [comment]
What browser are you using? I see something different in Chrome 67.0.3396.87 on macOS:

![image](https://user-images.githubusercontent.com/1924134/41617043-8119b89a-73cd-11e8-89e9-22d81bce9efc.png)

Can try in an incognito window without browser extensions?

**Comment by bontibon** [comment]
Yeah, looks like an extension is doing something. Thanks for the hint, @shurcooL.
