### ISSUE TITLE
Update WritersCanShare to False doesn't work

### ISSUE THREAD

**Issue by AlvarDev** [golang/gddo#566]
In google.golang.org/api/drive/v3

I'm translating an app from Python to Go, but I have an issue with WritersCanShare update:

- WritersCanShare = true works, the file property is updated from false to true

- WritersCanShare = false doesn't work, the file property never changes

**Comment by shantuo** [comment]
Hi there, this is the issue tracker for the website godoc.org, please file issue against their [repo](https://github.com/google/google-api-go-client/issues) instead.
