### ISSUE TITLE
Refreshing package failed, is now permanently 404'd

### ISSUE THREAD

**Issue by meme** [golang/gddo#571]
https://godoc.org/github.com/meme/itunes exists at https://github.com/meme/itunes. Once I updated the repository I had refreshed the page using the button at the bottom and a message stating that an internal error occurred had been shown. Now the package is a 404. How can I correct this issue to ensure that my documentation is available?

**Comment by dmitshur** [comment]
Your package is constrained to GOOS=windows GOARCH=amd64 only. However, godoc.org should be able to display windows/amd64-only packages, that is one of the environment it tries to use:

https://github.com/golang/gddo/blob/a475e0307621ec6832db210443de8f9ff6ff3148/doc/builder.go#L467

This seems like a bug.

**Comment by shantuo** [comment]
For a nonexistent package, gddo tries to fetch it by default, there is no need to refresh. I agree this seems to be a bug.

**Comment by dmitshur** [comment]
It should've worked with amd64-only restriction too.

I checked the logs, and I'm seeing errors like:

```
2018/08/17 18:37:10 web   fetch: 3 notfound: no Go files or subdirs github.com/meme/itunes
2018/08/17 18:37:10 rfrsh fetch: 856 notfound: no Go files or subdirs github.com/meme/itunes
```

That shouldn't be the case if the code to try different Go environments is working as expected:

https://github.com/golang/gddo/blob/a475e0307621ec6832db210443de8f9ff6ff3148/doc/builder.go#L558-L577

(But the actual issue might be elsewhere.)

A good next step is to run gddo locally and try to reproduce it, then understand why/how it happens.
