### ISSUE TITLE
all: redeploy crawler with Go 1.11

### ISSUE THREAD

**Issue by gkelly** [golang/gddo#573]
https://godoc.org/?q=http doesn't have net/http in the results.

This started happening in the past few hours.  The results have subpackages of net/http, but not the net/http package itself.  Searching for net/http still works, in that it goes to the exactly-matched package.

**Comment by shantuo** [comment]
This is because the crawler is not running Go 1.11.

**Comment by gkelly** [comment]
It's showing up again. Not sure what happened behind the scenes.

**Comment by dmitshur** [comment]
I've redeployed the crawler with Go 1.11 just now. We can keep an eye on it and see if it helps with the mentioned issues (including #575).
