### ISSUE TITLE
Shows information about removed sub-pkgs

### ISSUE THREAD

**Issue by andersfylling** [golang/gddo#588]
In my repository there are sub packages that were removed several weeks ago, and I have no idea how to completely reset/clear the GoDoc data so it can re-parse my project. Talking about the website, godoc.org.

Does anyone know?

**Comment by jackwilsdon** [comment]
Have you got a link to the project in question and the names of the subpackages which should no longer exist?

**Comment by andersfylling** [comment]
Yes, i tried refresh.

Here's a link: https://godoc.org/github.com/andersfylling/disgord#pkg-subdirectories

Pgks such as "rest", "state", and "resource" no longer exist. Although they might exist in forks.

**Comment by dmitshur** [comment]
Did you visit and refresh the actual packages that no longer exist? E.g.:

-	https://godoc.org/github.com/andersfylling/disgord/rest
-	https://godoc.org/github.com/andersfylling/disgord/state
-	etc.

I just did that, and they're no longer showing up at https://godoc.org/github.com/andersfylling/disgord/state.

**Comment by andersfylling** [comment]
Oh, thank you! I thought the refresh would refresh everything :D
