### ISSUE TITLE
Use Bitbucket API v2

### ISSUE THREAD

**Issue by shanab** [golang/gddo#599]
Hi,

I was planning to create a fork of this repo that adds support to pulling private Bitbucket repos (similar to the current support of private Github repos), when I noticed that you're using the old Bitbucket API to fetch Bitbucket repos. The old API is deprecated and soon all the endpoints will be removed, according to [this link](https://confluence.atlassian.com/bitbucket/version-1-423626337.html).
> Bitbucket Cloud v1 APIs are deprecated.
Bitbucket Cloud REST API version 1 is deprecated effective 30 June 2018. All 1.0 APIs will be removed from the REST API permanently on 12 April 2019

I'd be happy to work on a patch for this if you're open to it.

**Comment by dmitshur** [comment]
godoc.org has been redeployed with the fix ([CL 170279](https://golang.org/cl/170279)) now. /cc @arnottcr
