### ISSUE TITLE
all: deploy with Go 1.12

### ISSUE THREAD

**Issue by dmitshur** [golang/gddo#603]
Now that Go 1.12 is out, gddo should be updated for it. This involves:

- [x] Re-generate the standard library list in package `gosrc` ([CL 164301](https://golang.org/cl/164301)).
- [x] Deploy with Go 1.12.
    - https://godoc.org/cmd/go/internal/renameio should display package docs, rather than 404.

Previously #572 for Go 1.11.

/cc @andybons @shantuo @julieqiu

**Comment by myitcv** [comment]
@dmitshur has this landed yet? (there doesn't appear to be a way from a godoc.org page to see what version of Go is in use)

Either way, there appears to be an issue with the search index again

![Screen Shot 2019-03-14 at 11 16 28](https://user-images.githubusercontent.com/3374574/54353023-e1b88000-464a-11e9-9068-80ec188a1aa0.png)

Possibly a repeat of https://github.com/golang/gddo/issues/508

**Comment by dmitshur** [comment]
Thanks for reporting. The search index issue is a known consequence of the deploy not being done yet, as reflected by the status of this issue. It will be resolved when the deploy is done.

> (there doesn't appear to be a way from a godoc.org page to see what version of Go is in use)

You’ll be able to tell when it’s done when https://godoc.org/cmd/go/internal/renameio displays package documentation rather than 404 (it’s a package that’s new to 1.12).

**Comment by myitcv** [comment]
Thanks for confirming this issue is still outstanding.

> You’ll be able to tell when it’s done when https://godoc.org/cmd/go/internal/renameio displays package documentation rather than 404 (it’s a package that’s new to 1.12).

Perhaps a slightly more robust way of determining the Go version being "run" by godoc.org would be to include the version string in the page footer?

![Screen Shot 2019-03-14 at 13 08 20](https://user-images.githubusercontent.com/3374574/54359431-842c2f80-465a-11e9-9602-25d80187fe6a.png)

**Comment by dmitshur** [comment]
> Perhaps a slightly more robust way of determining the Go version being "run" by godoc.org would be to include the version string in the page footer?

I agree, that would be a helpful feature. There's already an open issue tracking it, see https://github.com/golang/gddo/issues/177. I've added your picture illustrating what it can look like there.

**Comment by dmitshur** [comment]
This is done now.

https://godoc.org/cmd/go/internal/renameio displays the docs for that new package, and searching for `fmt`, `http` finds the packages from standard library because they're installed without errors now.

Please let us know if you spot any issues.
