### ISSUE TITLE
splitdwraf runtime issue: "function main is undeclared in the main package"

### ISSUE THREAD

**Issue by nilajawill** [golang/gddo#622]
Hello,

While attempting to retrieve tools (mainly godoc) by using `go get golang.org/x/tools/cmd/...`, I keep running into an error thrown by `golang.org/x/tools/cmd/splitdwarf`. 

This is what I get in my shell:
> `go get golang.org/x/tools/cmd/...`
> `# golang.org/x/tools/cmd/splitdwarf`
> `runtime.main_mainÂ·f: function main is undeclared in the main package`

However, if I try to retrieve godoc directly via `go get golang.org/x/tools/cmd/godoc`, I do not receive this message.

This doesn't affect me at the moment, since I am just learning how to use Go, but I thought it would be beneficial to bring to the attention of more capable individuals.

If you need anymore information, I will gladly provide what I can.

Thank you very much!
Nilaja D Williams

**Comment by jackwilsdon** [comment]
I think you want to raise this issue with [golang/go](https://github.com/golang/go/issues), as that is the issue tracker for all [golang/tools](https://github.com/golang/tools) related things.

**Comment by nilajawill** [comment]
Oh! Okay, I will do that. Thank you very much!
