### ISSUE TITLE
Make Client.Close() more prominent in docs/examples

### ISSUE THREAD

**Issue by gbrener** [golang/gddo#623]
I encountered a "too many open files" error/panic when using the docker Golang client library as documented, and traced it back to this function: https://godoc.org/docker.io/go-docker#NewEnvClient . I solved the problem by calling the `Close()` method on the `*Client` object, but because this method is not being used in any of the examples, it took me a while to find it. Perhaps we can make `Close()` more prominent in the documentation somehow - and/or included in the existing examples - so that this doesn't bite more people in the future.

**Comment by arnottcr** [comment]
Are you suggesting that the godoc tool implement this change, or that the [go-docker repo](https://github.com/docker/go-docker) fix their documentation?

**Comment by gbrener** [comment]
Suggesting a documentation fix to the go-docker repo. I assume I should close this issue and repost there?
