### ISSUE TITLE
Missing variable type of `key` returned in func (*Tokenizer) TagAttr

### ISSUE THREAD

**Issue by kennykarnama** [golang/gddo#625]
Hi, i just want to confirm that, in go doc https://godoc.org/golang.org/x/net/html#Tokenizer.TagAttr, the `key` returned by the function is not descriptive. it should be added `key []byte`

![image](https://user-images.githubusercontent.com/26187880/58449873-a18b7880-8136-11e9-824b-1888c03396b4.png)

**Comment by jackwilsdon** [comment]
That is a standard Go shorthand for multiple values with the same type (`key, val []byte` means they're both bytes). This also isn't the repository for this issue, as this is simply the godoc.org website itself. If you have any issues with the net package you should open an issue against [golang/go](https://github.com/golang/go].
