### ISSUE TITLE
https://godoc.org/golang.org/x/sys/unix/aliases.go returns 500 Internal server error.

### ISSUE THREAD

**Issue by nyt-hughmandeville** [golang/gddo#640]
https://godoc.org/golang.org/x/sys/unix/aliases.go returns 500 Internal server error.

```
$ curl -i "https://godoc.org/golang.org/x/sys/unix/aliases.go"
HTTP/2 500
date: Fri, 09 Aug 2019 22:53:53 GMT
content-type: text/plain; charset=utf-8
content-length: 22
x-cloud-trace-context: 329a37b1d1b7dd019397c8be77ca25e7/1832251762085882494;o=1
via: 1.1 google

Internal server error.
```

**Comment by dmitshur** [comment]
The problem is here:

https://github.com/golang/gddo/blob/af0f2af80721261f4d211b2c9563f7b46b2aab06/gosrc/vcs.go#L294-L304

We're opening a directory and trying to read its contents, but not handling the error condition where the file exists but is not a directory. I'll send a fix.
