### ISSUE TITLE
Internal server error when viewing packages

### ISSUE THREAD

**Issue by theckman** [golang/gddo#670]
Hello,

The production instance is currently throwing ISEs when trying to view the documentation for any package. Is an on call engineer aware and investigating?

Cheers!

**Comment by theckman** [comment]
Quick update, now every URL is returning an internal server error for me. This is on Android, no difference in Incognito mode.

**Comment by MohsenElgendy** [comment]
can confirm it!

**Comment by matthew119427** [comment]
I seem to be getting 500s only on crypto/argon2.

**Comment by dmitshur** [comment]
Let's use https://github.com/golang/go/issues/36642 as the canonical issue to track this.

**Comment by cup** [comment]
https://github.com/golang/gddo/issues/669

https://github.com/golang/gddo/issues/670
https://github.com/golang/gddo/issues/671

**Comment by cup** [comment]
https://github.com/golang/gddo/issues/669

https://github.com/golang/gddo/issues/670
https://github.com/golang/gddo/issues/671
https://github.com/golang/go/issues/36642

**Comment by dmitshur** [comment]
Closing in favor of aforementioned issue.

See https://github.com/golang/go/issues/36642#issuecomment-577908050 for more details about what happened, including the root cause.
