### ISSUE TITLE
godoc.org: shows wrong import path for forked Go projects

### ISSUE THREAD

**Issue by mcandre** [golang/gddo#672]
https://godoc.org/github.com/JFrogDev/go-rpm/yum shows `import "github.com/JFrogDev/go-rpm/yum"`, whereas https://github.com/jfrog/go-rpm shows `import (
	"fmt"
	"github.com/cavaliercoder/go-rpm"
)`

**Comment by dmitshur** [comment]
I agree with @heschik's analysis. There doesn't seem to be a bug in godoc.org, it is displaying an accurate import path of the "github.com/JFrogDev/go-rpm/yum" Go package.

If you want to see documentation for the "github.com/cavaliercoder/go-rpm" package, you should visit https://godoc.org/github.com/cavaliercoder/go-rpm.

I'll close this, but please comment if I have misunderstood.
