### ISSUE TITLE
Godoc issue with go.mongodb.org/mongo-driver

### ISSUE THREAD

**Issue by eslindsey** [golang/gddo#675]
[This documentation for Decode](https://godoc.org/go.mongodb.org/mongo-driver/mongo#SingleResult.Decode) says that

> DecodeBytes will return

when it should say

> Decode will return

I don't think this is the right place to report this--this looks like the Godoc issue tracker and I suspect this belongs on the Mongo issue tracker. However, it wasn't obvious where to go to report a documentation error. Can someone point me in the right direction?

**Comment by jackwilsdon** [comment]
Looks like [mongodb/mongo-go-driver](https://github.com/mongodb/mongo-go-driver) is the repository you're looking for.

**Comment by eslindsey** [comment]
Thank you!
