### ISSUE TITLE
Unable to set connections.max.reauth.ms 

### ISSUE THREAD

**Issue by danchemla** [golang/gddo#677]
Hello,

I wanted to set the value of the broker `connections.max.reauth.ms` to force regular reauthentication of the consumer reading from my topics. 

However I could not find the possibility to set this property. Did I miss something ?

Thank you

**Comment by jackwilsdon** [comment]
This seems like an issue with a Kafka-related Go library — this repository is for https://godoc.org and isn't related to your problem.

**Comment by danchemla** [comment]
Indeed my mistake sorry
