### ISSUE TITLE
I can't figure out why you're hiding the scrollbar from the site, you idiot

### ISSUE THREAD

**Issue by zixiliuyue** [golang/gddo#681]
No scroll bar, too hard to drag
![image](https://user-images.githubusercontent.com/12575317/79969398-07f25580-84c4-11ea-935f-d19fe9718ef3.png)

**Comment by jackwilsdon** [comment]
What OS/browser are you on?

**Comment by dmitshur** [comment]
Please keep https://golang.org/conduct in mind when taking the time to report an issue.

The godoc.org website does not make a decision to hide the scrollbar. This appears to be a configuration option of the browser and/or operating system.
