### ISSUE TITLE
Marxist propaganda on the website

### ISSUE THREAD

**Issue by ivanjaros** [golang/gddo#684]
Hi,
I am seeing a marxist propaganda on the old and new website(https://godoc.org/, https://pkg.go.dev/), called Black Lives Matter.

Can you please remove it and stop forcing your own political views on the entire dev community that is mostly not even based in USA? 

If you want to virtue-signal to your own cronies, maybe put a geo ip filter in it so people from outside of USA are not being force-fed this crap. Here in Europe, we have experienced out own fair share of communism and we are definitely not looking to bring it back into fashion.

Cheers.

**Comment by dmitshur** [comment]
Please see https://github.com/golang/go/issues/41094#issuecomment-682574230.
