### ISSUE TITLE
GoDoc.org shows out of date package github:temporalio/temporal-go-sdk

### ISSUE THREAD

**Issue by flossypurse** [golang/gddo#688]
### What is the URL of the page with the issue?

https://godoc.org/github.com/temporalio/temporal-go-sdk

### What is your user agent?

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

### Screenshot
 

 
![Screen Shot 2020-09-03 at 2 31 52 PM](https://user-images.githubusercontent.com/34380806/92164245-4abd2600-edf2-11ea-89f7-90893045ed2a.png)

### What did you do?
 

Searched for "temporal go sdk"

### What did you expect to see?

The up-to-date package github.com:temporalio/go-sdk 
The up-to-date package is available via pkg.go.dev: https://pkg.go.dev/go.temporal.io/sdk

### What did you see instead?

This package no longer exists (github.com:temporalio/temporal-go-sdk)
We don't want the old out-of-date package to be published.

**Comment by dmitshur** [comment]
The repository at https://github.com/temporalio/temporal-go-sdk exists.

The problem here is that godoc.org is not module aware, so it doesn't know to read the go.mod file, where it's stated that the canonical import path is `go.temporal.io/sdk` rather than `github.com/temporalio/temporal-go-sdk`.

/cc @julieqiu

**Comment by cullywakelin** [comment]
Thanks Dmitri,
OK, so how do we "fix" that?

This repo DID exist https://github.com/temporalio/temporal-go-sdk but
redirects to https://github.com/temporalio/go-sdk -

Also, how come Go Docs doesn't reflect the new state - only the old? I.E
only temporal-go-sdk is shown, you can't find go-sdk there. You have to go
to pkg.go.dev to find the newest version -

Thanks

**Comment by dmitshur** [comment]
> OK, so how do we "fix" that?

There's nothing you need to do, this was fixed by making a module-aware package documentation available at pkg.go.dev, where as you said this works. Considering Please consider https://blog.golang.org/godoc.org-redirect, I don't think there's anything that needs to be done here.
