### ISSUE TITLE
Typo in package validator page @https://godoc.org/gopkg.in/bluesuncorp/validator.v5#hdr-Baked_In_Validators_and_Tags

### ISSUE THREAD

**Issue by setoken06** [golang/gddo#689]
I found typo in https://godoc.org/gopkg.in/bluesuncorp/validator.v5#hdr-Baked_In_Validators_and_Tags.

current
```
ne
	For strings & numbers, eq will ensure that the value is not
	equal to the parameter given. For slices, arrays, and maps,
	validates the number of items. (Usage: eq=10)
```

maybe
```
ne
	For strings & numbers, ne will ensure that the value is not
	equal to the parameter given. For slices, arrays, and maps,
	validates the number of items. (Usage: ne=10)
```

**Comment by alireza-ahmadi** [comment]
Hi @setoken06. Thanks for reporting this issue.

Godoc only extracts documentation from the packages' source codes so for fixing this typo, please create an issue in its [corresponding repository](https://github.com/go-playground/validator).
